### ISSUE TITLE
unable to get RNW working with on SSR side 

### ISSUE THREAD

**Issue by aleedmanath** [brillout/vite-plugin-ssr#513] opened 2022-11-14 23:17 UTC
### Description

I'm trying to use this plugin with React Native Web.

I've verified config below (aliasing RN to RNW) works in vanilla Vite project. 

But using with `ssr` plugin, the alias is not picked up, resulting import error due to trying to import `react-native` package.

It does seem like this plugin overrides config, so please recommend best approach or necessary fix for getting this working.

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import ssr from 'vite-plugin-ssr/plugin'

const reactNativeWeb = () => ({
  name: 'react-native-web-plugin',
  config: () => ({
    resolve: {
      alias: {
        extensions: [".web.jsx", ".web.js", ".jsx", ".js"],
        "react-native": "react-native-web",
      }
    }
  })
})

export default defineConfig({
  plugins: [
    reactNativeWeb(),
    react(),
    ssr()
  ],
})
```

### Error Stack

```shell
RN alias error: 

import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
```

**Comment by brillout** [comment] 2022-11-15 08:50
VPS doesn't actually alter the alias. So I'd need the two reproductions here: the one you have with RN working with vanilla Vite, and the other one with RN not working with vite-plugin-ssr.

**Comment by aleedmanath** [comment] 2022-11-15 15:01
Yesterday I learned how to make config fully work like RN/Expo Web using vanilla Vite, so going to try again and report back in case it was a mistake on my part

**Comment by aleedmanath** [comment] 2022-11-15 16:02
Yeah I'm unable to get a configuration that works in client and server.

But I see this is not a bug, as initially reported. 

@brillout Shall I close issue? or would you still be interested in looking into reproduction to see how we can resolve this for RNW users?

**Comment by aleedmanath** [comment] 2022-11-15 16:06
Hm @brillout i can't find any info in docs as to how config should be handled for client and server environments

Any advice would be appreciated as I imagine some RN dependencies need to be aliased, transpiled, or ignored for this to work

**Comment by brillout** [comment] 2022-11-15 16:59
Closing because I think it's a user land issue that should be fixable.

But if you have evidence that it's related to vite-plugin-ssr (ideally two reproductions as I described above), then I'm happy to have a look. I'll reopen then.

(FYI https://brillout.github.io/rules/.)

**Closed by brillout** 2022-11-15 16:59 UTC
Labels: Bug :boom:

**Comment by aleedmanath** [comment] 2022-11-15 21:54
i was able to get it working

looks like for some reason `resolve.alias` defined by a plugin was not being picked up, so needed to be at top level config

**Comment by brillout** [comment] 2022-11-15 22:03
👍 . Btw. contribution much welcome to create a react-native example. I'll then link it from the docs.
