### ISSUE TITLE
[HMR] New page and routes without server restart

### ISSUE THREAD

**Issue by vintlucky777** [brillout/vite-plugin-ssr#66] opened 2021-05-19 21:37 UTC
Currently if I have a server running, I can edit current pages and live reload works like a charm.
I can also add links into navigational component and they appear instantly.

However when I add new page files, these are not picked up until the server is restarted.
Is it possible to pick up pages and routes without restarting the server?

**Comment by brillout** [comment] 2021-05-19 21:44
I will have a look at it.

**Comment by brillout** [comment] 2021-05-20 14:32
The root cause is in Vite's source code. I'm working on a PR.

**Comment by brillout** [comment] 2021-05-21 13:07
Both PR are merged. Vite releases on Monday.

**Comment by brillout** [comment] 2021-05-26 08:57
Released in `0.1.0-beta.45`.

**Closed by brillout** 2021-05-26 08:57 UTC
Labels: awaiting :hourglass_flowing_sand:, being-worked-on :construction:, bug-vite :boom:
