### ISSUE TITLE
"is404" remains true

### ISSUE THREAD

**Issue by hamedg68** [brillout/vite-plugin-ssr#681] opened 2023-03-05 05:45 UTC
### Description

**_is404_** in _pageContext_ remains true  if _onBeforeRender_ is not provided for the page. here is the reproduction from vue-full example for this issue which shows if we are in 404NotFound page and we want to go to _Welcome_ and _Markdown_  page, _is404_ property remains true but for _Data Fetching_ and _Routing_ page which have _onBeforeRender_
_is404_ is updated

https://stackblitz.com/github/hamedg68/VPS-vue-full-is404

### Error Message + Error Stack

is404 not updated

**Comment by brillout** [comment] 2023-03-05 13:15
Indeed, I could reproduce. I'll have a look at it. It's most likely due to the Vue integration at `renderer/`, let's see.

**Comment by brillout** [comment] 2023-03-05 18:10
Fix released in `v0.4.91`.

**Closed by brillout** 2023-03-05 18:10 UTC
Labels: bug :boom:

**Comment by brillout** [comment] 2023-03-05 18:16
Going back to the 404 page now works.

Note that `is404` still remains `true` in your example because of the Vue integration.

AFAICT VPS itself hasn't any bug left.
