### ISSUE TITLE
Module not found on production build `0.4.0-beta.35`

### ISSUE THREAD

**Issue by jaybe78** [brillout/vite-plugin-ssr#342] opened 2022-06-17 13:43 UTC
### Description

After I've upgraded to version `0.4.0-beta.35`, there seems to be an issue with the `npm run prod` command.
It compiles correctly but when I try to reach the app I get an error.
`npm run dev` command seems to be working and the bug seems to have been introduce since `0.4.0-beta.35`.

Please find that repo to reproduce the issue:

https://github.com/jaybe78/vps-webpack5-redux-streaming-test

### Error Stack

```
> server:prod
> cross-env NODE_ENV=production node ./dist/main

[vite-plugin-ssr@0.3.64][Warning] `createPageRenderer()` is outdated, use `renderPage()` instead. See https://vite-plugin-ssr.com/renderPage
[vite-plugin-ssr@0.3.64][Warning] The options `root` and `isProduction` you passed to `createPageRenderer()` have no effect anymore: they are now automatically determined.
Server running at http://localhost:3000
Error: Cannot find module '7105'
    at webpackEmptyContext (file:///Users/jb/Documents/vps-webpack5-redux-streaming-test/dist/main.js:83252:10)
    at getImporterFilePath (file:///Users/jb/Documents/vps-webpack5-redux-streaming-test/dist/main.js:83149:87)
    at loadDistEntries (file:///Users/jb/Documents/vps-webpack5-redux-streaming-test/dist/main.js:83102:24)

```

**Comment by brillout** [comment] 2022-06-19 21:22
Doesn't seem to be related to vps?

If you make the reproduction minimal (reduce the number of dependencies) then I'll have a look at it. Ideally minimal modification starting from `$ npm init vite-plugin-ssr`.

**Comment by brillout** [comment] 2022-06-20 08:46
> After I've upgraded to version `0.4.0-beta.35`

I don't see how the new beta version could lead to that webpack error. So I'm guessing you also did something else.

Closing but let me know if you are confident this error to be caused by vps. Happy to re-open if it's a vps problem.

**Closed by brillout** 2022-06-20 08:46 UTC
Labels: Bug :boom:

**Comment by jaybe78** [comment] 2022-06-20 14:38
Hi @brillout  

Well I've removed most dependencies and just left what's below.


```
"@vitejs/plugin-react": "^1.3.2",
    "express": "^4.18.1",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "react-streaming": "^0.2.13",
    "vite": "^2.9.12",
    "vite-plugin-environment": "^1.1.1",
    "vite-plugin-ssr": "0.4.0-beta.38"
```
  

The application is very simple. It only display 2 routes component in which there's basically nothing.    

The only change I bring in the code which makes the app crash is to update to `0.38`. As soon as I downgrade back to `0.33`, ti works.

I'm not saying it's specific to VPS, it could a be a combination of using VPS with `react-streaming`. I'm not sure but I've tried everything.

If you could please double check this branch and see for yourself, I think there's something odd.

https://github.com/jaybe78/vps-webpack5-redux-streaming-test/tree/bug/cannot-find-module

**Comment by brillout** [comment] 2022-06-20 16:43
Neat, I'll have a look at it.

**Comment by brillout** [comment] 2022-06-21 19:47
I'll have a look at it tomorrow. (Sorry for the late handling of this, but the truth is that I'm skeptical this is a vps bug. I'll have a look at it nevertheless.)

**Comment by jaybe78** [comment] 2022-06-22 09:19
@brillout np. 
I agree it's probably not specific to vps only, but still odd that the crash started occurring when upgrading vps.
Let's first find out if you can reproduce the issue on your side. If you do others might encounter the same issue.

**Comment by brillout** [comment] 2022-06-22 20:52
Could reproduce and I think I know what's going on. Will fix it tentatively tomorrow.

**Comment by jaybe78** [comment] 2022-06-23 08:24
@brillout Is it related to vps in the end ?

**Comment by jaybe78** [comment] 2022-06-23 11:32
NP ! Thanks for looking into this. You were right it was not related to vps itself but one of its dependencies.
