### ISSUE TITLE
Render hook gets called twice if Vite's splitVendorChunkPlugin is used.

### ISSUE THREAD

**Issue by rivatove** [brillout/vite-plugin-ssr#691] opened 2023-03-08 19:47 UTC
### Description

Reproduction:
1. Clone https://github.com/rivatove/vps-repro-691
2. Run npx vite build
3. Run npx vite preview
4. Render hook gets called twice on page load (see console)

**Comment by brillout** [comment] 2023-03-08 22:52
The problem is that `splitVendorChunkPlugin()` includes both Server Routing and Client Routing into the same bundle. This means your app ends up using both Server Routing and Client Routing at the same time.

I'd use Rollup's `manualChunks` instead of `splitVendorChunkPlugin()`.

Just [commited](https://github.com/brillout/vite-plugin-ssr/commit/116f66eef391020a2b8158e6cf2afc4145015eff) a new wrong usage error helping you know whether you are correctly bundling things  (released as draft `vite-plugin-ssr@0.4.91-draft.86055`).

```js
[vite-plugin-ssr@0.4.91][Wrong Usage] Server Routing and Client Routing both loaded. Make sure your
client-side code doesn't load both at the same time.
```

**Closed by brillout** 2023-03-08 22:52 UTC
Labels: bug :boom:
