### ISSUE TITLE
Problem with tailwindcss + postcss-import

### ISSUE THREAD

**Issue by Semdevmaster** [brillout/vite-plugin-ssr#298] opened 2022-04-07 09:41 UTC
During development, all style files are loaded through the link tag,
and immediately after them, style tags with the same content are loaded
![links](https://user-images.githubusercontent.com/2706508/162167491-2908f4f2-7fde-4730-889e-9d9c522babba.jpg)
Why load the same styles twice?

When using, for example, tailwindcss along with postcss-import, this leads to an error, since all css files are loaded onto the page separately with @import, although they are only needed at the build stage via postcss-import and should result in only one file

Without vite-plugin-ssr in development mode, vite only loads style tags without copies as link tags
How can I turn it off?

**Comment by brillout** [comment] 2022-04-07 10:04
This is by design, in order to avoid the style flashing between the browser receiving the HTML and the browser receiving the JS bundle that will inject the CSS.

> When using, for example, tailwindcss along with postcss-import, this leads to an error, since all css files are loaded onto the page separately with @import, although they are only needed at the build stage via postcss-import and should result in only one file

Can you elaborate?

**Comment by Semdevmaster** [comment] 2022-04-07 10:56
This is my style.css
![image](https://user-images.githubusercontent.com/2706508/162182466-e5573d68-6671-46a8-862a-183b21b8d689.png)
As a result, after the postcss-import plugin has run, you should get one file
But
![image](https://user-images.githubusercontent.com/2706508/162183199-654089bd-b896-4d42-836e-0ef6b18e14cc.png)
And result after refreshing page
![image](https://user-images.githubusercontent.com/2706508/162183481-bf2a0701-5987-4b10-ac0f-f43546b4292d.png)
if you block the download of these files in the network tab in the browser, then everything works fine. So my question is - how can I disable the loading of these files during development?

**Comment by brillout** [comment] 2022-04-07 11:24
https://github.com/brillout/vite-plugin-ssr/issues/262 will enable you to do that.

**Comment by brillout** [comment] 2022-04-08 12:18
Marking this as a feature request since most Tailwind users don't have this problem. It's probably something specific to your setup.

**Comment by brillout** [comment] 2022-04-08 12:21
Closing this in favor of https://github.com/brillout/vite-plugin-ssr/issues/300.

**Closed by brillout** 2022-04-08 12:21 UTC
