### ISSUE TITLE
Question: How would could I change the directory path for pages

### ISSUE THREAD

**Issue by aFuzzyBear** [brillout/vite-plugin-ssr#93] opened 2021-06-10 16:26 UTC
Hello 

Firstly, thanks for putting in the time to make such an awesome toolchain, after much searching, Im actually liking your wee setup, its brilliant. Currently modding mine to the lastest react 18 and seeing if the new SSR implementation works.

Thing is I would like to change the location of the pages folder from `./pages/` to `./src/pages/` 
The setup I tend to use is similar to the CRA struc, (it kinda stuck with me)

```
./
- node_modules
- build/dist 
- public //static
- src
- src/App/App.js etc
- src/Components/UIComponents
- src/Pages/ <- This is where I would like him,
```

Is that at all possible??

Many Thanks bud,

**Comment by brillout** [comment] 2021-06-10 17:26
Hello @aFuzzyBear

Yes, simply `mv pages/ src/`. (The Filesystem Router uses the common ancestor directory as root.)

> if you need a hand with the writing some doc's for this plugin, I'd be happy to
> Currently modding mine to the lastest react 18 and seeing if the new SSR implementation works.

I'm interested in playing around with React Server Components. Is that something you'd be interested in exploring? I'd gladly accept a PR for an example `/examples/react-server-components/` 😊.

**Comment by aFuzzyBear** [comment] 2021-06-10 22:34
Hey bud , 
lol Im just a novice atm man, just learning about the back end, only recently learnt about docker. Then I came across the ssr problem with Snowpack, and well thats where I threw in the towel with them, then it was actually your repo that got me looking at vite properly,

Server components, do look extremely interesting.  I just dont know enough about it it at the moment, hopefully once the react core get it closer to alpha the better, I have this idea of a really fast and efficient stack so I can then start my freelancing gig, I do want to learn more about this, and hopefully contribute to this project in some ways,

**Comment by brillout** [comment] 2021-06-11 06:29
> Server components, do look extremely interesting

Yes there are, that's why I'm particularly excited to see an integration between Server Components and Vite/`vite-plugin-ssr`.

If you feel ambitious (I think you should ;-)), we can create an official boilerplate for React Server Components + Vite.

> hopefully once the react core get it closer to alpha the better

Details will change but I expect the Server Components core design to not change much; the paradigm shift will remain the same.

**Comment by brillout** [comment] 2021-06-11 06:30
I'm closing the ticket since the original issue is addressed by https://github.com/brillout/vite-plugin-ssr/commit/a87fbbae03c880d531e5a29aaae0111ca6c185e1.

**Closed by brillout** 2021-06-11 06:30 UTC

**Comment by Dema** [comment] 2021-06-12 11:33
There's a bug when I move pages to src in dev mode (server:prod mode is working)
Steps to reproduce
1. Run  `yarn create vite-plugin-ssr`
2. Select `react-ts`
3. `cd vite-project`
4. Move pages to ./src/pages
5. Run `yarn dev`
6. Open http://localhost:3000/

I get `Cannot GET /` in browser and 
```
yarn dev
yarn run v1.22.10
warning package.json: No license field
warning ../../package.json: No license field
$ npm run server

> server
> ts-node ./server

Pre-bundling dependencies:
  react
  react-dom
  vite-plugin-ssr/client
(this will be run only when your dependencies or config have changed)
Server running at http://localhost:3000
14:32:50 [vite] Error when evaluating SSR module /src/pages/_default/_default.page.server.tsx:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/tmp/vite-ssr-project/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/tmp/vite-ssr-project/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
14:32:50 [vite] Error when evaluating SSR module /src/pages/_default/_default.page.server.tsx:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/tmp/vite-ssr-project/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
in server console

**Comment by brillout** [comment] 2021-06-12 13:55
@Dema See https://github.com/brillout/vite-plugin-ssr/issues/94
