### ISSUE TITLE
How can I map parameterized route in homepage? 

### ISSUE THREAD

**Issue by develladin** [brillout/vite-plugin-ssr#60] opened 2021-05-16 18:17 UTC
Hello People, 

I'm trying to create blog on this tool with vue, but I don't know how to map `/posts/:post` in homepage? my setup: WindiCSS, Markdown, Vue (without TS) and of course `vite-plugin-ssr`. Is it possible to do this using tools I have?

If you don't understand something, please write, then I will describe this.

Thank You

**Comment by brillout** [comment] 2021-05-16 18:19
> map /posts/:post in homepage

What do you mean?

**Comment by develladin** [comment] 2021-05-16 18:36
Thank You for fast answer :D I mean:

showing (iterating like `map()` function in JS) parameterized route in homepage and making a link to this route. Then writing a markdown (with frontmatter) in `/posts/:post` (`:post` should be a vue components with Markdown, code is writted below).

```vue
<template>
  <h2>{frontmatter.title}</h2>
  <p>{frontmatter.description}</p>
  <MarkdownContent/>
  <p>{frontmatter.author}<p>
</template>
<script>
  import { frontmatter } from '~/posts/hello-world.md';
  const { title, description, author } = frontmatter;
</script>
```

PS: I'm new to vue, I still don't know how2 do some things in Vue ;)

**Comment by brillout** [comment] 2021-05-16 18:45
I see.

So, you have a list of blog posts somewhere saved in a variable, let's say `myBlogPosts`.

You add that variable to `contextProps.pageProps`:

```js
// .page.server.js

const myBlogPosts = /* your logic to retrieve your list of blog post */

export function addContextProps() {
  const pageProps = {
    myBlogPosts
  }
  return { pageProps }
}

// We make `contextProps.pageProps` available to the browser
export const passToClient = ['pageProps']
```

Then you pass `contextProps.pageProps` to your Vue root component as decribed in the docs.

Then you generate the list of `<a>` links using `pageProps.myBlogPosts` and using Vue's `v-for` attribute: `<li v-for="post in myBlogPosts">`.

**Comment by develladin** [comment] 2021-05-16 19:04
I need to check this tomorrow. Thank You so much.

**Comment by brillout** [comment] 2021-05-16 19:07
👍

I'm closing this since it's not a bug nor feature request.

But feel free to keep me updated if you run into a major headache situation :-).

**Closed by brillout** 2021-05-16 19:07 UTC
