### ISSUE TITLE
Error When use Koa as the backend server and an example of Vite + Solidjs as frontEnd

### ISSUE THREAD

**Issue by azhezzz** [brillout/vite-plugin-ssr#799] opened 2023-04-21 04:41 UTC
### Description

When using Koa as the backend server and [example of Vite + Solidjs](https://github.com/brillout/vite-plugin-ssr/tree/main/examples/solid-ssr) as frontEnd, if returning with `pipe()`, the console shows an error. It works properly when returning with `await getBody()`.

```
var { createServer } = require("vite");
var Koa = require("koa");
var koaConnect = require("koa-connect");
var { renderPage } = require("vite-plugin-ssr/server");

const root = `${__dirname}/`;

async function main() {
  const app = new Koa();

  const viteServer = await createServer({
    root,
    server: { middlewareMode: true },
    appType: "custom",
  });

  app.use(koaConnect(viteServer.middlewares)).listen(3000, () => {
    console.log("start listen on " + 3000);
  });

  app.use(async (ctx, next) => {
    const pageContextInit = {
      urlOriginal: ctx.request.originalUrl,
    };

    const pageContext = await renderPage(pageContextInit);
    const { httpResponse } = pageContext;
    if (!httpResponse) return next();

    const { earlyHints, pipe, getBody } = httpResponse;
    ctx.res.writeEarlyHints?.({
      link: earlyHints.map((e) => e.earlyHintLink),
    });

    // its ok
    // ctx.body = await getBody();
    ctx.body = pipe(ctx.res);
  });
}

main();

```

Here's a minimal reproduction:

https://replit.com/@azhezzz/AppropriateTroubledPassword

### Error Message + Error Stack

```shell
useClientRouter.js?v=b53d167b:129 Error: [vite-plugin-ssr@0.4.115][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Go to https://github.com/brillout/vite-plugin-ssr/issues/new and copy-paste this error. (The error's stack trace is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Don't hesitate to reach out as it makes vite-plugin-ssr more robust.
    at getPageContextSerializedInHtml (getPageContextSerializedInHtml.js?v=b53d167b:7:5)
    at getPageContextFirstRender (getPageContext.js?v=b53d167b:29:33)
    at getPageContext (getPageContext.js?v=b53d167b:21:16)
    at fetchAndRender (useClientRouter.js?v=b53d167b:124:41)
fetchAndRender @ useClientRouter.js?v=b53d167b:129
await in fetchAndRender（异步）
useClientRouter @ useClientRouter.js?v=b53d167b:57
（匿名） @ entry.js:7
```

**Comment by brillout** [comment] 2023-04-21 06:29
Thanks for the bug report.

Replit gives me:

```js
We ran into an internal error.
The repl didn't wake up in time. Please try again in 30 seconds.
```

Can you publish the reproduciton on GitHub? That'd be the best.

**Comment by azhezzz** [comment] 2023-04-21 09:47
@brillout  Thanks for the prompt reply.
OK. I have publish it to the GitHub 

https://github.com/azhezzz/koa_vite_solidjs_ssr

**Comment by brillout** [comment] 2023-04-21 09:50
The problem is that HTML is truncated:

```html
<!DOCTYPE html>
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="[/renderer/PageLayout.css?direct](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/renderer/PageLayout.css?direct)">
        <script type="module" defer>
import("/@vite/client");
import("/@fs/workspace/koa_vite_solidjs_ssr/node_modules/vite-plugin-ssr/dist/esm/client/router/entry.js");
</script>
        <meta charset="UTF-8" />
        <link rel="icon" href="[/renderer/logo.svg](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/renderer/logo.svg)" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="App using Vite + vite-plugin-ssr" />
        <title>Vite SSR app</title>
        <script>(e=>{let t=e=>e&&e.hasAttribute&&(e.hasAttribute("data-hk")?e:t(e.host&&e.host instanceof Node?e.host:e.parentNode));["click", "input"].forEach((o=>document.addEventListener(o,(o=>{let s=o.composedPath&&o.composedPath()[0]||o.target,a=t(s);a&&!e.completed.has(a)&&e.events.push([a,o])}))))})(window._$HY||(_$HY={events:[],completed:new WeakSet,r:{},fe(){},init(e,t){_$HY.r[e]=[new Promise((e=>t=e)),t]},set(e,t,o){(o=_$HY.r[e])&&o[1](t),_$HY.r[e]=[t]},unset(e){delete _$HY.r[e]},load:e=>_$HY.r[e]}));</script><!--xs-->
      </head>
      <body>
        <div id="page-view"><div data-hk="0-0-0-0-0" style="display:flex;max-width:900px;margin:auto"><div data-hk="0-0-0-0-1-0" style="padding:20px;flex-shrink:0;display:flex;flex-direction:column;align-items:center;line-height:1.8em"><div data-hk="0-0-0-0-1-1-0" style="margin-top:20px;margin-bottom:10px"><a href="[/](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/)"><img src="[/renderer/logo.svg](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/renderer/logo.svg)" height="64" width="64" alt="logo"></a></div><a data-hk="0-0-0-0-1-2-0" href="[/](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/)" class="navitem is-active">Home</a><a data-hk="0-0-0-0-1-3-0" href="[/about](https://3000-azhezzz-koavitesolidjss-d1naaic5m69.ws-eu94.gitpod.io/about)" class="navitem">About</a></div><div data-hk="0-0-0-0-2-0" style="padding:20px;padding-bottom:50px;border-left:2px solid #eee;min-height:100vh"><h1 data-hk="0-0-0-0-2-1-0-0">Welcome</h1><div data-hk="0-0-0-0-2-1-0-1">This page is:<ul><li>Rendered to HTML.</li><li>Interactive. <!--#--><button data-hk="0-0-0-0-2-1-0-2-0" type="button">Counter <!--#-->0<!--/--></button><!--/--></li></ul></div></div></div>Not Found
```

The end is missing.

**Comment by brillout** [comment] 2023-04-21 09:53
It seems like something's wrong with Koa's streaming support?

Closing but I'll reopen if there is evidence that the problem is on VPS's side.

**Closed by brillout** 2023-04-21 09:53 UTC
Labels: bug :boom:
