### ISSUE TITLE
vanilla-extract missing CSS with HTML-only rendering (in dev only)

### ISSUE THREAD

**Issue by astahmer** [brillout/vite-plugin-ssr#538] opened 2022-12-07 00:26 UTC
### Description

Hey, first I wanted to thank you for all your work, i'm very glad to see how far VPS has got and also excited to see where it's going (especially the single file RFC 👀 ) !

# Context:
- [vanilla-extract](https://vanilla-extract.style/) is a CSS-in-JS lib with mostly no runtime, except when using the `sprinkles` package
- i'm trying to use VPS with HTML-only pages (.page.server) since it would be a nice match (0 runtime CSS from VE + 0 runtime JS from VPS), but then found that styles are missing after visiting a page that has client-side JS sent (.page.client) in dev only, it works fine when using `vite build` + `vite preview`
- maybe related to https://github.com/brillout/vite-plugin-ssr/issues/411

it (VE in SSR in dev) works fine with other frameworks (rakkas/qwik/next, havent tried others) or others rendering modes of VPS, which makes me think this might be a VPS problem
i've been digging a lot today and couldn't find a way to fix this in the VE-plugin, i'm no expert in making vite plugin so it might also just be me not being good enough in that field

# Steps to reproduce
[minimal repro](https://github.com/astahmer/ve-dev-ssr-bug-repro)

- pnpm i
- pnpm dev
- visit localhost:3000
- go to `zero-js` page, see there the CSS is there, everything is ok (even tho [this line was forced to true](https://github.com/astahmer/ve-dev-ssr-bug-repro/blob/main/ve-plugin.ts#L34), was needed in the VE plugin, without it there was no CSS at all for the HTML-only page..)
- you can visit any page that has no client-side js (=you can't visit "with-js" page) and the CSS will still be fine
- then visit the `with-js` page, everything is still fine
- go back to `zero-js` page, the CSS for that page is gone and won't ever come back unless completely stop+restarting the vite dev server

this is what happens : 
![Kapture 2022-12-07 at 01 04 08](https://user-images.githubusercontent.com/47224540/206052891-3cfff957-3acd-4c99-aa72-0dc4ff2e4130.gif)

# Workaround

[I have found a workaround](https://github.com/astahmer/ve-dev-ssr-bug-repro/blob/main/pages/zero-js.page.client.tsx#L3), with this the CSS will not be missing when using HTML-only pages (`.page.server` + `ssr({ includeAssetsImportedByServer: true})`)

this is what happens when I use a .page.client & dynamic import the sprinkles manually in dev mode only, what expected would happen :
![Kapture 2022-12-07 at 01 05 27](https://user-images.githubusercontent.com/47224540/206053724-e1035104-742d-49a8-85bd-016785bd7eae.gif)

please tell me if there's anything I can do to help !

**Comment by brillout** [comment] 2022-12-07 08:27
I could reproduce indeed. Although I sometimes couldn't reproduce and I needed to restart the server to be able to reproduce again. I'd guess it's some kind of race condition between Vite picking up the CSS dependency and VE's generation of CSS.

Vite automatically injects the CSS, so it's not really a VPS thing.

(Note that `includeAssetsImportedByServer` has no effect in dev, it's only a build thing.)

The only thing VPS does here is to collect the CSS dependencies to avoid FOUC: https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/node/renderPage/getPageAssets/retrieveAssetsDev.ts. You can dig into this file (`node_modules/vite-plugin-ssr/dist/cjs/node/renderPage/getPageAssets/retrieveAssetsDev.js`) which will give you insightful information about how Vite analyzes your app.

While I think it's probably unrelated to VPS, maybe there is a possible workaround on VPS's side.

**Comment by astahmer** [comment] 2022-12-07 16:47
ok didnt know that about `includeAssetsImportedByServer` !

yes retrievePageAssets is one of the 3 places that I stumbled upon yesterday and thought that could help, I also found:
- https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/node/plugin/plugins/extractAssetsPlugin.ts#L119
- https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/utils/styleFileRE.ts

I have no idea what to do with that tho
I tried once more fixing it in VE-plugin and it seems ok with these 2 commits:

- fixed the html-only CSS, but lost HMR on those pages:
https://github.com/astahmer/ve-dev-ssr-bug-repro/commit/acaf592a151bb9b88625d5e6f48c630ef303034b

- fixed HMR:
https://github.com/astahmer/ve-dev-ssr-bug-repro/commit/3490aca3c905734133e7556507eb066defca9353

so I guess we can close this unless you want to make a workaround on VPS's side too ?

**Comment by brillout** [comment] 2022-12-08 17:03
This really seems more like a VE thing than a VPS thing. So let's close this.

Let me know if you believe there is anything VPS can do here.

Btw. in case your company would be up for it: https://github.com/sponsors/brillout.

**Closed by brillout** 2022-12-08 17:03 UTC
Labels: needs-investigation 🔎

**Comment by lukasholzer** [comment] 2022-12-18 10:20
@astahmer hey have you opened a PR or bug on the VE repository? Running in the same issue here and would prefer having VE supporting that instead of writing the plugin on my own 😬

**Comment by astahmer** [comment] 2022-12-18 10:45
I did open a PR ([here](https://github.com/vanilla-extract-css/vanilla-extract/pull/942)) but not specific for that bug, although it does fix it among other things

I made an usage example with vite-plugin-ssr [here](https://github.com/astahmer/box-extractor/tree/refactor/monorepo/examples/react-vite-plugin-ssr)

**Comment by brillout** [comment] 2022-12-21 13:19
Did you move the example? Your links gives a 404. Thanks for the example! We should add it to the community example list.

**Comment by astahmer** [comment] 2022-12-21 13:27
yeah sorry, I updated the comment above with a [permalink instead](https://github.com/astahmer/box-extractor/tree/356c1aa88d46df10b73d8349f59c6d4a8a9c34eb/examples/react-vite-plugin-ssr)
this is early/experimental, since I kinda have to maintain a nightmare with local npm links & .tgz in published module (while waiting for my PR to VE to be merged) and getting different behaviour between both.. 


btw i'll soon open another issue, this time I fixed it directly in VPS [here](https://github.com/brillout/vite-plugin-ssr/blob/main/vite-plugin-ssr/node/plugin/plugins/extractAssetsPlugin.ts#L151)

not much details but as a summary: this is due to `.css` being loaded from an external package (published on npm) shipped as `.css.ts` (VE's way of styling) imported directly into the consuming package (user-code)

**Comment by brillout** [comment] 2022-12-21 13:42
>  i'll soon open another issue

I see, looking forward to it. (FYI we may not even need that with https://github.com/vitejs/vite/pull/11430. But it may take a while until the PR is merged, so let's go for your proposed fix in the meantime.)

**Comment by airtonix** [comment] 2024-01-31 21:29
@brillout Even after https://github.com/vitejs/vite/pull/11430 got merged, i still had to make use of the vite NX plugin in the vite config for packages in my nx monorepo to be resolved in Vike.


```ts
import react from '@vitejs/plugin-react'
import vike from 'vike/plugin'
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import { UserConfig } from 'vite'
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin'; // This

const config: UserConfig = {
  plugins: [
    nxViteTsPaths(),                                                       // This
    react(),
    vanillaExtractPlugin(),
    vike({
      prerender: true
    })
  ]
}

export default config
```

**Comment by airtonix** [comment] 2024-01-31 22:41
https://github.com/airtonix/vike-vanilla-extract-onRenderHtml-bug-538/tree/master#readme

**Comment by brillout** [comment] 2024-02-01 09:26
@airtonix Can you make it minimal starting from one of the boilerplates (`npm init vike@latest`)?

**Comment by brillout** [comment] 2024-02-08 11:09
@airtonix I guess that `global.css.ts` isn't real CSS: it's a JavaScript file that dynamically generates and inserts CSS on the fly on the client-side, right?

This won't work if you import `global.css.ts` from a file like `+onRenderHtml.tsx` which is never loaded on the client-side.

Importing real CSS from `+onRenderHtml.tsx` works because Vike can tell it's CSS and thus adds it to the client-side. But I don't see how this can work for `global.css.ts` because, technically speaking, it isn't CSS.

(I didn't run your reproduction, but I can do so if you remove all frivolous/unknown dependencies from `package.json`)
