### ISSUE TITLE
React + TS boilerplate is broken

### ISSUE THREAD

**Issue by Dema** [brillout/vite-plugin-ssr#77] opened 2021-05-27 13:03 UTC
# Steps to reproduce
1. run `yarn create vite-plugin-ssr`
2. Select react + ts
3. run `yarn && yarn dev`
4. Open http://localhost:3000/

This error appears:
```
$ ts-node ./server
Server running at http://localhost:3000
18:57:25 [vite] Error when evaluating SSR module /pages/_default/_default.page.server.tsx:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/main-frontend/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/main-frontend/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
18:57:25 [vite] Error when evaluating SSR module /pages/_default/_default.page.server.tsx:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/home/dema/main-frontend/node_modules/vite/src/node/ssr/ssrModuleLoader.ts:127:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by brillout** [comment] 2021-05-27 13:04
Let me have a look

**Comment by brillout** [comment] 2021-05-27 13:06
I cannot reproduce, what's your Node.js version and OS?

**Comment by Dema** [comment] 2021-05-27 13:09
I have node v12.22.0 on Arch Linux.

**Comment by brillout** [comment] 2021-05-27 13:11
Let me check.

**Comment by Dema** [comment] 2021-05-27 13:12
Yeah, it works on v14.16.0

**Comment by brillout** [comment] 2021-05-27 13:14
Seems like a Vite issue with older Node.js versions. If someone reading this could create a ticket at https://github.com/vitejs/vite and investigate that'd be great. I'm closing this in the meantime.

@Dema Glad it works for you now. Let me knof if you have questions about vite-plugin-ssr.

**Closed by brillout** 2021-05-27 13:14 UTC

**Comment by brillout** [comment] 2021-05-27 13:17
;-)
