### ISSUE TITLE
Styles are not loaded in production build CSR navigation

### ISSUE THREAD

**Issue by RainArroDev** [brillout/vite-plugin-ssr#324] opened 2022-05-14 09:29 UTC
Hello!

I'm using CSR and SSR loading. 

In production when page is loaded in SSR then styles are added to <head>.
When I navigate back to previous page or navigate to a new page in CSR styles are not added to <head> 

Could this be a bug or is something wrong with my setup?

**_default.page.client.ts**
```
import { createApp } from './app';
import { getPageTitle } from './getPageTitle';
import { useClientRouter } from 'vite-plugin-ssr/client/router';

import type { PageContext } from '@root/types/page';
import type { PageContextBuiltInClient } from 'vite-plugin-ssr/client/router';

let app: ReturnType<typeof createApp>;

useClientRouter({
  render(pageContext: PageContextBuiltInClient & PageContext) {
    if (!app) {
      app = createApp(pageContext);
      app.mount('#app');
    } else {
      app.changePage(pageContext);
    }

    console.log('pageContext', pageContext);

    const title = getPageTitle(pageContext);
    if (title) {
      document.title = title;
    }
  },
  // Vue needs the first render to be a hydration
  ensureHydration: true,
  prefetchLinks: false,
  onTransitionStart,
  onTransitionEnd,
});

function onTransitionStart() {
  console.log('Page transition start');
  document.querySelector('.content')?.classList.add('page-transition');
}

function onTransitionEnd() {
  console.log('Page transition end');
  document.querySelector('.content')?.classList.remove('page-transition');
}

```

**_default.page.server.ts**
```
import { renderToString } from '@vue/server-renderer';
import { escapeInject, dangerouslySkipEscape } from 'vite-plugin-ssr';
import { createApp } from './app';

import type { PageContextBuiltIn } from 'vite-plugin-ssr';
import type { PageContext } from '@root/types/page';

export const passToClient = ['pageProps', 'urlPathname', 'documentProps'];

export async function render(pageContext: PageContextBuiltIn & PageContext) {
  const app = createApp(pageContext);
  const appHtml = await renderToString(app);

  // See https://vite-plugin-ssr.com/head
  const { documentProps } = pageContext;
  const title = documentProps?.title || 'Motory';
  const description = documentProps?.description || 'Buy and sell cars!';

  const documentHtml = escapeInject`<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${description}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600&display=swap" rel="stylesheet" media="print" onload="this.media='all'">
        <title>${title}</title>
      </head>
      <body>
        <div id="app">${dangerouslySkipEscape(appHtml)}</div>
      </body>
    </html>`;

  return {
    documentHtml,
    pageContext: {
      // We can add some `pageContext` here, which is useful if we want to do page redirection https://vite-plugin-ssr.com/page-redirection
    },
  };
}

```

**Comment by brillout** [comment] 2022-05-14 09:44
Closing this ticket because it's not clear enough.

But publish a minimal reproduction starting off `npm init vite-plugin-ssr` with clear instructions with what you expect to happen, and I'll have a look.

**Closed by brillout** 2022-05-14 09:44 UTC

**Comment by RainArroDev** [comment] 2022-05-14 20:40
Hi! Thanks for your reply. 

I created a minimal repo https://github.com/RainArroDev/-vite-plugin-ssr-minimal
I used this example as a base https://github.com/brillout/vite-plugin-ssr/tree/master/examples/vue-full

How to reproduce:

- Run the app in prod build (npm run prod)
- Load index page in SSR (styles are loaded)
- Navigate to `/random` route
- Reload the page
- Navigate to `/index` route (styles are not loaded)

**Comment by RainArroDev** [comment] 2022-05-14 20:52
#315 Seems to be the same problem. I see you concluded this was a Windows and Vite problem. I'm also using Windows so lets ignore this bug for now :)
