### ISSUE TITLE
Deploy to Vercel

### ISSUE THREAD

**Issue by mjarkk** [brillout/vite-plugin-ssr#98] opened 2021-06-14 08:31 UTC
Hello, i'm currently using Heroku to deploy a site build using this plugin but want to switch to Vercel *if that's even possible*.  
I have tried to deploy my site on vercel by myself but cannot succeed so i was wondering is this even possible and if so could you add some documentation for that.

**Comment by brillout** [comment] 2021-06-14 08:33
Hello,

Yes, AFAICT you can deploy any Node.js app to Vercel so it should be possible.

> I have tried to deploy my site on vercel by myself but cannot succeed

Problem?

> documentation for that.

👍

**Comment by mjarkk** [comment] 2021-06-14 08:52
> Problem?

It's company internal code :( cannot share that but i'll try to re-create it in an example repo

**Comment by brillout** [comment] 2021-06-14 08:57
You can try to deploy a boilerplate `$ npm init vite-plugin-ssr` to Vercel and see if that works. If it works then you know the problem is not on `vite-plugin-ssr`'s side but somewhere else in your stack.

**Comment by mjarkk** [comment] 2021-06-14 14:03
This is the error i'm getting:
```
2021-06-14T13:56:50.190Z	28ae95f0-8b14-4808-9097-773f97d5b8fa	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot find module './pageFiles.node'
Require stack:
- /var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js
- /var/task/node_modules/vite-plugin-ssr/dist/cjs/index.js
- /var/task/server/index.js
- /var/task/___vc_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js","reason":{"errorType":"Error","errorMessage":"Cannot find module './pageFiles.node'
Require stack:
- /var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js
- /var/task/node_modules/vite-plugin-ssr/dist/cjs/index.js
- /var/task/server/index.js
- /var/task/___vc_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js","code":"MODULE_NOT_FOUND","requireStack":["/var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js","/var/task/node_modules/vite-plugin-ssr/dist/cjs/index.js","/var/task/server/index.js","/var/task/___vc_launcher.js","/var/runtime/UserFunction.js","/var/runtime/index.js"],"stack":["Error: Cannot find module './pageFiles.node'","Require stack:","- /var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js","- /var/task/node_modules/vite-plugin-ssr/dist/cjs/index.js","- /var/task/server/index.js","- /var/task/___vc_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)","    at Function.resolve (internal/modules/cjs/helpers.js:94:19)","    at requireResolve (/var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js:46:16)","    at setPageFiles (/var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js:12:5)","    at Object.getPageFiles (/var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/getPageFiles.shared.js:28:35)","    at Object.getPageIds (/var/task/node_modules/vite-plugin-ssr/dist/cjs/route.shared.js:129:55)","    at renderPage (/var/task/node_modules/vite-plugin-ssr/dist/cjs/renderPage.node.js:40:45)","    at /var/task/server/index.js:30:26","    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)","    at next (/var/task/node_modules/express/lib/router/route.js:137:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cannot find module './pageFiles.node'","Require stack:","- /var/task/node_modules/vite-plugin-ssr/dist/cjs/page-files/setup.node.js","- /var/task/node_modules/vite-plugin-ssr/dist/cjs/index.js","- /var/task/server/index.js","- /var/task/___vc_launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:388:22)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred
```

I get this error on 2 types of deployments:
- Running a express server by using using @vercel/node ([code](https://github.com/mjarkk/vercel-vite-ssr-test/tree/d1cbc69c409a7fbe48adc53de0d37f060fe6ab3e))
- Using the vercel api folder ([code](https://github.com/mjarkk/vercel-vite-ssr-test/tree/e07b200a90f0a7c37edfff984e2d5d1aafa8e9bb))

Other info:
- Build command on vercel: `npm run build`
- Output directory on vercel: `dist/client`

**Comment by brillout** [comment] 2021-06-14 17:14
Seems like Vercel is building your Node.js code (probably with Webpack). Does importing `/dist/server/importer.js` solve the probelm? This is how Cloudflare Workers deployments work with vite-plugin-ssr (https://github.com/brillout/vite-plugin-ssr#cloudflare-workers).

```js
// Your Node.js server entry that Vercel will build

// This helps Webpack resolve dependency paths
import './path/to/dist/server/importer.js';

// For example if you use Vercel serverless functions
module.exports = (req, res) => {
   // ...
}
```

**Comment by mjarkk** [comment] 2021-06-14 21:24
Tried to do what you suggested but cannot get the `importer.js` imported tried different paths and require and import but nothing worked :(.  

I also ran: 
```js
const items = fs.readdirSync('.') // also checked ..
throw(JSON.stringify(items));
```
That didn't include the dist folder so that's probably why the above didn't work.

Also the more i read about vercel the more i start to think it's not made for the on request based server side rendering. On the other hand they seem to support frameworks like nuxt with that feature.

**Comment by brillout** [comment] 2021-06-14 21:31
> That didn't include the dist folder so that's probably why the above didn't work.

I see. Hm, that's quite surprising actually.

How do people deploy a TypeScript written Node.js server to Vercel then? They need to build the TS code and access the build in production.

I see two options:
 - Build locally and then deploy to Vercel, so that the `dist/` folder will be there from the get go.
 - Explore this custom build thing that Vercel has. (I'm not familar with it but I'm thinking there may be a way to access the build output then,)

**Comment by brillout** [comment] 2021-06-14 21:33
> Also the more i read about vercel the more i start to think it's not made for the on request based server side rendering. On the other hand they seem to support frameworks like nuxt with that feature.

Yes it should be possible. Maybe exploring the build for Nuxt and Next.js could shine some light on how to access `dist/`.

**Comment by mjarkk** [comment] 2021-06-15 08:04
Ah just came across something,  
To support on request based ssr in nuxt you need to use a custom backend [nuxt/vercel-builder](https://github.com/nuxt/vercel-builder), [nuxt docs about this](https://nuxtjs.org/docs/2.x/deployment/vercel-deployment)  
I haven't looked into the repo much yet but i think we might need something equal

**Comment by brillout** [comment] 2021-06-17 10:11
I believe everything is ready from `vite-plugin-ssr`'s side. (The main trick here is to `import 'dist/server/importer.js'` in the server entry.)

AFAICT, the only thing needed is someone digging into how to access the `dist/` directory.

Contribution welcome 😊.

**Comment by brillout** [comment] 2021-06-17 19:20
Btw https://vercel.com/support/articles/how-can-i-use-files-in-serverless-functions

This is what vite-ssr uses to deploy to Vercel:

https://github.com/frandiox/vitesse-ssr-template/blob/fa916beb9ae7e29f81a01f6710c577e3898aae1d/serverless/api/index.js#L3-L4

https://github.com/frandiox/vitesse-ssr-template/blob/fa916beb9ae7e29f81a01f6710c577e3898aae1d/serverless/vercel.json#L5

**Comment by Hugo01** [comment] 2021-06-23 19:08
Any news on this issue? i'm having the same problem
a step by step to deploy a vite-ssr application to vercel would be much appreciated
thanks

**Comment by brillout** [comment] 2021-06-24 07:38
The unresolved question is how to require/import the `dist/server/importer.js` file.

The problem being that Vercel doesn't expose the `dist/`.

Maybe Vercel builds the server code *before* it runs the build?

There is a way to access `dist/server/importer.js` as a file but then you have to do something like https://github.com/frandiox/vitesse-ssr-template/blob/fa916beb9ae7e29f81a01f6710c577e3898aae1d/serverless/api/index.js#L3-L4. What happens then with the `require()` calls inside `dist/server/importer.js`?

Someone would need to dig into these questions, hence the `contribution-welcome` label :-).

**Comment by mjarkk** [comment] 2021-06-26 13:43
Got something further, I've now removed the `dist` folder from the `.gitignore` and now the route returns js data.  
Site: https://vercel-vite-ssr-test-hu8hg547w-mkopenga.vercel.app/  
Response:
```js
import{o as e,c as o,F as n,b as r}from"./vendor.6e5e68da.js";const l={},a=r("h1",null,"About",-1),t=r("p",null,"A colored page.",-1);l.render=function(r,l){return e(),o(n,null,[a,t],64)};export default l;
```

**Comment by mjarkk** [comment] 2021-06-26 14:17
Eyy got a deployment working: https://vercel-vite-ssr-test-q1letqq4w-mkopenga.vercel.app/  
It's not perfect but here's how i did it:

## Codebase
### Build code
**Do this before every commit**
```sh
npm run build
```

#### `vercel.json` *(added)*
```json
{
    "version": 2,
    "functions": {
        "api/index.js": {
            "includeFiles": "dist/**"
        }
    },
    "rewrites": [
        {
          "source": "/((?!assets/).*)",
          "destination": "/api/index.js"
        }
    ]
}
```
#### `.gitignore`
```diff
diff --git a/.gitignore b/.gitignore
index 2c5b3c9..1ea7020 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,4 +1,3 @@
 node_modules
 .DS_Store
-dist
 *.local
```
#### `api/index.js` *(added)*
```js

import { createPageRender } from 'vite-plugin-ssr';
import '../dist/server/importer.js';
import { resolve } from 'path';

const renderPage = createPageRender({ isProduction: true, root: resolve(__dirname, '..') });

module.exports = async (req, res) => {
    const result = await renderPage({
        url: req.url,
        pageProps: {},
    });
    if (result.nothingRendered) res.status(200).send('');
    else res.status(result.statusCode).setHeader("content-type", "text/html").send(result.renderResult);
}
```

## Inside Vercel:
![image](https://user-images.githubusercontent.com/15320763/123515732-f5137c00-d698-11eb-8d4f-7000e02d6b9d.png)

**Comment by brillout** [comment] 2021-06-26 20:00
Neat & thanks for sharing.

A solution to the "build locally and commit dist/" problem would be a new command `vite-plugin-ssr bundle`. But I'm not sure (yet) what it should do exactly.

**Comment by mjarkk** [comment] 2021-06-26 23:47
I've also hooked into a vercel discussion with the same problem, i would say lets wait for someone from vercel to comment on this because if you would ask me this is a big limitation: https://github.com/vercel/vercel/discussions/6393

**Comment by brillout** [comment] 2021-06-27 05:41
Nice, let's see the replies.

**Comment by brillout** [comment] 2021-07-15 07:18
Can `includeFiles` be used to access files generated at build-time?

`includeFiles` seems to work only for files that are committed to Git.

Reproduction:
 1. Deploy https://github.com/brillout/vercel-test.
 2. Go to `/some-non-root-url`.
 3. Watch the function logs and see that `build/` is not included even though `vercel.json#functions['api/index.js'].includeFiles` is set to `build/**`. Note how `package.json#scripts.build` generates `build/someFile.js`.

**Closed** 2021-07-16 11:16 UTC
Labels: contribution-welcome :two_hearts:

**Comment by brillout** [comment] 2021-07-16 11:38
The trick is to use an npm script `vercel-build` instead of a `build` script. See https://vite-plugin-ssr.com/vercel.

**Comment by mjarkk** [comment] 2021-07-16 12:40
Thank you very much!!
