### ISSUE TITLE
`npm init vite-plugin-ssr@latest` not working

### ISSUE THREAD

**Issue by cdll** [brillout/vite-plugin-ssr#272] opened 2022-02-25 07:46 UTC
I 've started with [`pnpm init vite-plugin-ssr@latest`](https://vite-plugin-ssr.com/scaffold)with choosing `react-ts` option, after coming into the created folder and installing the deps with pnpm, neither the starting scripts `pnpm dev` nor `pnpm server:watch` work well on requesting `http://localhost:3000`, on the other side, i 've got elder `vite-plugin-ssr@0.1.0-beta4`. 

Even though i 've upgraded `vite-plugin-ssr` to `v3`, it doesnt work well with the created project.

Could any body give some help? thanks all the same. 🙏

**Comment by brillout** [comment] 2022-02-25 07:48
Let me try

**Comment by brillout** [comment] 2022-02-25 07:50
Can't reproduce.

Feel free to create an *exact* step-by-step reproduction. Closing in the meantime.

**Comment by brillout** [comment] 2022-02-25 07:51
Ah I'm seeing you used `pnpm init`, let me see.

**Closed by brillout** 2022-02-25 07:50 UTC

**Comment by brillout** [comment] 2022-02-25 07:54
Also can't reproduce any problem with `pnpm init vite-plugin-ssr@latest`.
