### ISSUE TITLE
Error: [vite-plugin-ssr@0.4.26][Bug] You stumbled upon a bug in vite-plugin-ssr's source code

### ISSUE THREAD

**Issue by rawb1t** [brillout/vite-plugin-ssr#429] opened 2022-08-25 15:06 UTC
### Description

An error occured when I try to open a sub page with an anchor.

For example:
http://localhost:3000/en-US/foobar#anchor

### Error Stack

```shell
at getFileUrl (getFileUrl.js:30:9)
    at retrievePageContextFromServer (getPageContext.js:125:28)
    at onBeforeRenderExecute (getPageContext.js:101:45)
    at async getPageContextUponNavigation (getPageContext.js:55:33)
    at async fetchAndRender (useClientRouter.js:86:35)
    at async globalThis.__vite_plugin_ssr__navigate (useClientRouter.js:36:9)
    at async navigate (useClientRouter.js?v=51950d0c:171:5)

at pushHistoryState (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/history.js:70:20)
    at pushHistory (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/history.js:47:9)
    at changeUrl (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:254:5)
    at fetchAndRender (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:129:9)
    at async globalThis.__vite_plugin_ssr__navigate (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:36:9)
    at async navigate (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js?v=51950d0c:171:5)
```

**Comment by brillout** [comment] 2022-08-25 15:25
I need the full line `Error: [vite-plugin-ssr@0.4.26][Bug] You stumbled upon a bug in vite-plugin-ssr's source code...`. (It contains debug information at the end of the error message.)

**Comment by rawb1t** [comment] 2022-08-25 20:00
Error: [vite-plugin-ssr@0.4.26][Bug] You stumbled upon a bug in vite-plugin-ssr's source code. Reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes vite-plugin-ssr more robust.

Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/en-US/foobar#anchor'.

**Comment by brillout** [comment] 2022-08-25 20:03
What is the content of the line `at getFileUrl (getFileUrl.js:30:9)`?

What value do you pass to `navigate(value)`?

**Comment by rawb1t** [comment] 2022-08-25 20:21
No, I didn't pass anything to `navigate()`. Everything works fine if I pass it to `navigate()`.

It only happens if I type it this address including the anchor directly into the address box or whenever i hit enter and an anchor address is in the address box.

Seems to be a problem with the History API

**Comment by brillout** [comment] 2022-08-26 07:39
I'll need a reproduction.

**Comment by rawb1t** [comment] 2022-08-26 13:46
I believe this error occures since your last update with the anchor bug in `navigate()`. Afaik everything works fine when I opened a page with anchor in its URL before

**Comment by brillout** [comment] 2022-08-27 10:59
I could not reproduce: clicking on `<a href=/star-wars#foo />` doesn't throw any error, and then reloading the page doesn't throw any error either.

Closing. Feel free to provide a reproduction and I'll have a look at it.

**Closed by brillout** 2022-08-27 10:59 UTC
Labels: Bug :boom:

**Comment by rawb1t** [comment] 2022-08-27 21:15
A link doesn't couse the bug as I said. It only appears if you type the address with an anchor in the address box of the browser and hit enter to open it.

When I type this address: http://localhost:3000/en-US/foobar#anchor into the address bar of the browser and hit enter, the error occures but it doesnt occure if you are navigationg through the page either via a ordinary link or via navigate. Only if you open the url via the browser's address bar

**Comment by rawb1t** [comment] 2022-08-28 21:06
```
Uncaught (in promise) DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/digital-menu#section-balance'.
    at pushHistoryState (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/history.js:70:20)
    at pushHistory (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/history.js:47:9)
    at changeUrl (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:254:5)
    at fetchAndRender (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:129:9)
    at async globalThis.__vite_plugin_ssr__navigate (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js:36:9)
    at async navigate (http://localhost:3000/node_modules/vite-plugin-ssr/dist/esm/client/router/useClientRouter.js?v=928864fa:171:5)
```

It appears in history.js, line 70

```
function pushHistoryState(state, url) {
    window.history.pushState(state, '', url); // Error appears here
}
```

It definetly still appears and has nothing to do with any other plugin.

**Comment by brillout** [comment] 2022-08-29 06:24
I'll need a reproduction, as I said.

**Comment by rawb1t** [comment] 2022-08-29 11:06
I already stated how I come across this bug and I provided all the Stacks, what else can I do to help?

**Comment by brillout** [comment] 2022-08-29 13:01
https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

https://antfu.me/posts/why-reproductions-are-required

**Comment by rawb1t** [comment] 2022-08-29 13:35
Nevermind, it seems like the Plugin is colliding with the `navigate` function within a hashchange listener

I removed the hashchange listener, now it seems to work. Thank you
