### ISSUE TITLE
Allow returning string (unsafe) from render

### ISSUE THREAD

**Issue by deckchairlabs** [brillout/vite-plugin-ssr#92] opened 2021-06-10 02:59 UTC
I would like to be able to return a string (unsafe) from a server render without having to sanitize with the `html` export, perhaps this could be an opt-in config option?

**Comment by deckchairlabs** [comment] 2021-06-10 03:10
I guess this also opens the issue of how to inject the script tags, which it seems `html` is doing.

And, I have also realized I can just render to a node stream to get around the unsafe return from a render, so not sure if this would still be needed.

**Comment by brillout** [comment] 2021-06-10 09:18
What is your overall goal?

**Comment by deckchairlabs** [comment] 2021-06-10 11:21
The ability to render the entire html document from the framework would be nice, html/head etc.

**Comment by brillout** [comment] 2021-06-10 12:53
Would the following work for you?

```js
import { html } from "vite-plugin-ssr";

export function render(pageContext) {
  let documentHtml = /* Whole HTML document rendered by the framework */
  documentHtml = html.injectAssets(documentHtml)
  documentHtml = html.dangerouslySkipEscape(documentHtml)
  return documentHtml
}
```

**Comment by deckchairlabs** [comment] 2021-06-10 12:59
Amazing!

**Comment by brillout** [comment] 2021-06-10 13:00
How urgent do you want this? I can implement it now if you want :-).

**Comment by deckchairlabs** [comment] 2021-06-10 13:01
Ha! Not Urgent at all, although I suppose this will introduce an issue with a markup mismatch when hydrating client side?

**Comment by brillout** [comment] 2021-06-10 13:04
No because you have full control over what's happening in the client.

The `html.injectAssets` actually injects *your* `.page.client.js` script.

AFAICT exposing `injectAssets` to users should do the trick.

**Comment by deckchairlabs** [comment] 2021-06-11 05:03
Would it be possible to determine the assets for the page by url?

So I'm planning to server render *ALWAYS* no pregen/static export or anything like that. It would be great to be able to call something like `getAssetsByUrl('/about')` and it would return an array of all the assets required by that URL.

Doing it that way I would either be able to pass those to my pageContext server side, and even additionally set HTTP2 push for those assets.

**Comment by brillout** [comment] 2021-06-11 05:42
How about `pageContext.pageAssets`?

```js
// _default.page.server.js

import { html } from "vite-plugin-ssr"

export function render(pageContext) {
  const { pageAssets } = pageContext
  const htmlPromise = /* ... */;
  return {
    pageAssets,
    htmlPromise,
    /* Or if you use streams:
    htmlStream,
    */
  }
}
```

```js
// server.js

const { createPageRender } = require('vite-plugin-ssr')

const renderPage = createPageRender(/*...*/)
app.get('*', async (req, res, next) => {
  const url = req.originalUrl
  const pageContext = { url }
  const { renderResult } = await renderPage(pageContext)
  const { htmlPromise, pageAssets } = renderResult
  http2.push(pageAssets)
  const html = await htmlPromise
  res.send(html)
})
```

**Comment by deckchairlabs** [comment] 2021-06-11 05:59
Oh I do like that

**Comment by brillout** [comment] 2021-06-11 17:53
I'll release the solution tentatively tomorrow.

**Comment by brillout** [comment] 2021-06-13 19:23
Tomorrow, hopefully :-)

**Comment by brillout** [comment] 2021-06-15 19:17
I'm 97% done, I'll release tomorrow :-)

**Comment by deckchairlabs** [comment] 2021-06-16 04:05
Oh wow, just saw that branch. More work than I thought it would have been!

**Comment by brillout** [comment] 2021-06-16 05:52
Yea I've done a pretty deep internal refactor which I've been wanting to do for quite some time. The neat thing here is that everything revolves around `pageContext` now internally as well.

**Comment by brillout** [comment] 2021-06-16 13:18
Btw. https://evertpot.com/http-2-push-is-dead/

**Comment by brillout** [comment] 2021-06-16 13:25
But https://evertpot.com/http/103-early-hints is great

**Comment by deckchairlabs** [comment] 2021-06-16 14:08
> Btw. https://evertpot.com/http-2-push-is-dead/

Aw heck, can't believe I missed that!

**Comment by brillout** [comment] 2021-06-16 17:33
Implemented https://github.com/brillout/vite-plugin-ssr/tree/master/examples/custom-server-render-integration

I will release a new version tomorrow morning. (I can't risk releasing before going to sleep since the refactor is quite profound.)

> Aw heck, can't believe I missed that!

https://news.ycombinator.com/over?points=300 that's how I ensure I don't miss anything important :-). (That's how I got the news.)

**Comment by brillout** [comment] 2021-06-16 17:33
A new version of `vite-plugin-ssr` tomorrow *

**Comment by brillout** [comment] 2021-06-17 10:05
Released in `0.1.2`.

See `html._injectAssets()` and `pageContext._pageAssets`in https://github.com/brillout/vite-plugin-ssr/tree/master/examples/custom-server-render-integration.

I added the prefix `_` to communicate that these are non-documented beta features subject to breaking changes. For now you are the only one using them and I'll let you know if there is a breaking change.

After a while we will remove the prefix and add documentation.

**Closed by brillout** 2021-06-17 10:05 UTC
Labels: being-worked-on :construction:

**Comment by deckchairlabs** [comment] 2021-06-17 10:28
> Released in `0.1.2`.
> 
> See `html._injectAssets()` and `pageContext._pageAssets`in https://github.com/brillout/vite-plugin-ssr/tree/master/examples/custom-server-render-integration.
> 
> I added the prefix `_` to communicate that these are non-documented beta features subject to breaking changes. For now you are the only one using them and I'll let you know if there is a breaking change.
> 
> After a while we will remove the prefix and add documentation.

Amazing, I'm going to start playing with it now!

**Comment by lukasluecke** [comment] 2021-07-22 16:19
@brillout I found this issue while trying out the new React 18 streaming server renderer, and thought I could somehow use these utilities to pass the required assets to the client to load. However after trying for quite some time, I think it's not possible yet.

Do you maybe have any hints for me? There's a reference implementation using React & Webpack at https://codesandbox.io/s/festive-star-9hfqt

**Comment by brillout** [comment] 2021-07-22 16:28
> pass the required assets

What assets?

>  I think it's not possible yet

Could you elaborate?

I didn't try React 18 streaming yet but I'm more than happy to assit you.

**Comment by lukasluecke** [comment] 2021-07-22 16:41
The assets that would usually get injected into the HTML. The demo directly references the files by source on the server side, and then uses a manifest on the client side to load some specific files manually (it's just a PoC, so not really representative).

I'll try to explain in more detail what I'm missing exactly later / tomorrow, maybe you could take a look at the link above in the mean time? Thank you already for your time! (and for this great plugin, spent all day prototyping a migration of a big NextJS application 😅)

**Comment by brillout** [comment] 2021-07-22 17:50
I will later today :-)

**Comment by brillout** [comment] 2021-07-22 21:34
I just had a look and it seems that it should work with `vite-plugin-ssr`. I may have missed some details though.

As for the assets:
 - Use `pageContext._pageAssets` to fully control the HTML generation. 
 - Add it to `export const passToClient = ['_pageAssets']` to be able to fully generate the HTML on the client-side as well.

The rest is related to Express.js and React so it should work with `vite-plugin-ssr` as well.

Also the webpack config doesn't seem to do anything special and Vite should work equally well.

Looking forward to see a React 18 streaming example 😍.

**Comment by lukasluecke** [comment] 2021-07-22 22:03
Well I was unable to get the asset paths resolved, it's just the server include paths (like `/pages/test.page.tsx`) that are available in `_pageAssets`, right? I did dig around inside of the `_injectAssets` part and the private functions for resolving the module / dependency paths and stuff as well, but didn't find any public access for those.

(Also I noticed that `.css` imports inside of the `_default.page.client.tsx` were not included, only if I put them inside of a specific page? Not sure if I did something wrong, or if that's by design)

I'll be sure to create an example out of it if I get it working 🙂

**Comment by brillout** [comment] 2021-07-23 08:38
`_pageAssets` includes the URLs of the assets, not their filesystem paths. Fo example, if you look at the URLs you'll notice they all start with `/assets/` since all assets live at `dist/client/assets` and that `dist/client/` is the directory that is statically served.

And I believe this is exactly what you need for React streams.

Or are you trying to get the asset's filesystem paths? Why so?

> (Also I noticed that `.css` imports inside of the `_default.page.client.ts` were not included, only if I put them inside of a specific page? Not sure if I did something wrong, or if that's by design)

The `.css` assets should be included as well. Also those imported in `_default.page.client.ts`. If they are not it's a `vite-plugin-ssr` bug.

> I'll be sure to create an example out of it if I get it working 🙂

Exciting 👀.

**Comment by lukasluecke** [comment] 2021-07-23 12:26
I got confused by the dev server asset urls 🙈 

Getting closer now to something working (the SSR DOM contains scripts and styles and renders more or less as expected, however the hydration is not working yet.

<img width="1276" alt="CleanShot 2021-07-23 at 13 20 20@2x" src="https://user-images.githubusercontent.com/6652670/126780763-f1c42c9c-1732-4c4c-86d1-bc7cdf35dbe3.png">
There is no useful error stack though, so I'm not sure how related this error is to my issues.

I'll comment again when I have a specific question or issue 😅

**Comment by brillout** [comment] 2021-07-23 12:30
Nice, looking forward to see your results :-).

> There is no useful error stack though

No *useful* stack trace or no strack trace at all?

Give me a strack trace and I'll dig into why you are getting this error.

**Comment by lukasluecke** [comment] 2021-07-23 12:49
<img width="407" alt="CleanShot 2021-07-23 at 13 40 20@2x" src="https://user-images.githubusercontent.com/6652670/126782994-c7e2b667-56d5-4865-82e2-4f15d0ce3963.png">

The Unhandled Promise Rejection was swallowing the trace - the SSR page context wasn't being passed through.

I have modified the server part to use `html._injectAssets` now on the initial response HTML, which seems to work (getting an interactive page). However now the server DOM and client DOM are not matching, which React complains about on hydrate (and I'm not sure if this partially defeats the purpose of the streaming, if this includes more assets that are required initially now - need to investigate further).

I'll play around a bit more, and let you know if I need more help 🙂

**Comment by brillout** [comment] 2021-07-23 13:02
Makes sense.

Maybe [`suppressHydrationWarning`](https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning) can help.

I believe the demo also hydrates the assets (i.e. injects the asset tags), in case the HTML streaming breaks down. But I'm wondering how often that happens and, more importantly, if it's really worth it do the wohle asset hydration dance only for such case that, while in theory possible, I'd assume in practice unusual. The asset HTML tags should be part of the first HTML bits to be streamed anyways.

So maybe we can skip the asset hydration thing.

**Comment by brillout** [comment] 2021-07-27 14:16
@lukasluecke Any news? A new user may need vite-plugin-ssr + React streaming.

And btw do you happen to know how Google crawls HTML streams? I guess Google waits until the HTML stream closes? That'd be huge for users with slow data that need to have first-class SEO.

**Comment by lukasluecke** [comment] 2021-07-27 14:32
Sorry, no news yet. I went with an SPA approach for my PoC now, just to get the remaining parts working first.

I'll try to have another go sometime this week, but can't promise anything.

Regarding the asset hydration, I think you might be right, that if we just include them in the initial stream response, we shouldn't need anything else, since the injected scripts take care of loading everything else afterwards. I'm not sure how that works with React.lazy and other code-splitting behaviours though.

Not sure how Google handles this specifically, but there is https://developers.google.com/search/docs/advanced/javascript/dynamic-rendering, which could mean just skipping the streaming part for the crawler, and sending the "full" content instead (which in case of `ReactDOM.renderToString` will just contain fallback content for any encountered Suspense boundary, if using React 18)

**Comment by brillout** [comment] 2021-07-27 16:25
> I'm not sure how that works with React.lazy and other code-splitting behaviours though

Vite handles that for you; if you have a dynamic `import()` in your code then Vite will automatically do code-splitting. So it should just work.

> there is [...] dynamic-rendering

Yea that would work but Google may penalize the slower page load. Would be quite neat if crawlers wait for HTML streams to end (that's what I'd assume). Then Google would both treat ours pages as fast and be able to crawl the content. Let's see if we can get more infos at https://stackoverflow.com/questions/68548197/seo-crawlability-impact-of-html-streaming.

**Comment by brillout** [comment] 2021-08-19 11:42
@lukasluecke Is your attempt published somewhere on GitHub? @orenelbaum is interested in implement streaming.

**Comment by jfsiii** [comment] 2021-08-23 14:52
@brillout if I understand correctly,  @lukasluecke is working on the React 18 streaming, but I'd like to know if there's support for the existing [`renderToNodeStream`]( https://reactjs.org/docs/react-dom-server.html#rendertonodestream)? I think it'd be incredibly useful to be able to stream the HTML response as early as possible, but I get that it may not be easy.

It seems like they'll require the same shifts in `render` or `injectAssets` from sync to async and from fully rendered string to a stream. 

Here's one example of using `renderToNodeStream`

https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/82ccd045264753c11966c59bb63dcba76b8b9f5c/react-streaming-ssr/server.js#L83-L113

What sticks out to me in that example is the [the first write](https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/82ccd045264753c11966c59bb63dcba76b8b9f5c/react-streaming-ssr/server.js#L98) includes the `<head>` assets, which it seems we may not know until the render stream is complete.

```js
const BEFORE = `
<!DOCTYPE html><html><head>
  <script type="module" defer src="/build/client.js"></script><link rel="stylesheet" href="/style.css"></head>
  <body><div id="approot">
`.replace(/\n\s*/g, '');
```

Maybe the names are stable enough we could assume them at the beginning? Maybe [the final write](https://github.com/GoogleChromeLabs/progressive-rendering-frameworks-samples/blob/82ccd045264753c11966c59bb63dcba76b8b9f5c/react-streaming-ssr/server.js#L108) could `append*` some assets to `<head>`? I'm quite new to this code so just thinking out loud.

WDYT about splitting this into a separate ticket on streaming responses vs continuing in this closed issue?
