### ISSUE TITLE
pageProps aren't updated on first page with ClientRouter

### ISSUE THREAD

**Issue by vopaldragon** [brillout/vite-plugin-ssr#308] opened 2022-04-15 15:25 UTC
repro:

1. with vue-full example, run app with SSR+SPA mode(no prerender)

`vite build && vite build --ssr`
`cross-env NODE_ENV=production ts-node ./server`

2. access to http://localhost:3000/hello/alice and then, click /hello/eli

3. URL changes and client gets appropriate pageContext.json  , but name prop will not update.

Once you change to other page(component) and back to /hello, it becomes to work correctly. So, maybe first hydration does not work well.
This does not occur on dev mode.

**Comment by brillout** [comment] 2022-04-15 19:51
I can't reproduce: the app renders `Hi eli.`, as expected.

**Comment by vopaldragon** [comment] 2022-04-15 23:22
Maybe my environment is inadequate, but I can reproduce it with Chrome/Firefox@Win11.

There may not be misunderstanding, but I forked repository and changed pacakge.json a bit.

https://github.com/vopaldragon/vite-plugin-ssr/tree/master/examples/vue-full

```
npm install
npm run prod
```
http://localhost:3000/hello/alice
Then, click hello/eli or /hello/jon

**Comment by brillout** [comment] 2022-04-16 06:01
Sill can't reproduce.

git clone https://github.com/brillout/vps-repod-308
pnpm install
pnpm run prod
I click on `Routing` then I see `Hi alice`
I clikc on `hello/eli` then I see `Hi eli`

**Comment by vopaldragon** [comment] 2022-04-16 07:47
What happen if you click Routing, and then reload the browser, and then, ckick hello eli?
I mean, this problem occurs only when s component is rendered by SSR and routing to the same component happen on client.
If I render(hydrate) page on / and move to /hello, as you write, it works on my environment.

**Comment by brillout** [comment] 2022-04-17 07:26
I could reproduce. Let me have a look.

**Comment by brillout** [comment] 2022-04-17 07:57
Seems like a Vue bug: https://github.com/brillout/vps-repod-308/commit/9b0e750c6752ce989aa7dcba8fc9a91aee08dcee. As you can see per the `console.log()` the `rootComponent.pageProps` is updated. But, somehow, Vue doesn't pick up the change.

**Comment by brillout** [comment] 2022-04-17 08:17
The `render()` is rightfully re-triggered, with the right `pageProps`: https://github.com/brillout/vps-reprod-308/commit/020e2b470d6b36dbd8ac9792cc3e5638e9ad183d.

Why doesn't Vue update `hello/index.page.vue`?

**Comment by vopaldragon** [comment] 2022-04-17 09:41
Vue seems to update the page, because `onUpdated` lifecycle hook is triggered (https://github.com/brillout/vps-reprod-308/pull/1). I could avoid the problem using `usePageContext()`.

**Comment by brillout** [comment] 2022-04-17 09:43
Is there a way to make it work without using this hack? This does seem like a Vue bug to me.

**Comment by vopaldragon** [comment] 2022-04-17 12:06
I can create minimal reproducing code without vite-plugin-ssr.

[https://github.com/vopaldragon/ssr-vue](https://github.com/vopaldragon/ssr-vue)

I'm asking on vue-forum now.

**Comment by brillout** [comment] 2022-04-17 20:04
👍 Keep me updated.

Closing since it's a Vue bug.

**Closed by brillout** 2022-04-17 20:04 UTC

**Comment by brillout** [comment] 2022-04-21 08:09
Any news on that? Is there a ticket on Vue's repository to follow?

It would be good to update vue-full with a fix.

**Comment by vopaldragon** [comment] 2022-04-21 12:26
I couldn't get response on forum, so I created [issue](https://github.com/vuejs/core/issues/5771).

**Comment by brillout** [comment] 2022-05-10 12:00
The issue was fixed. Next Vue patch will include it.
