### ISSUE TITLE
Passing renderers programmatically

### ISSUE THREAD

**Issue by pepicrft** [brillout/vite-plugin-ssr#276] opened 2022-03-09 15:07 UTC
👋🏼 First of all, thanks a lot for this amazing plugin.
I'm playing with it to build a framework upon it, and I was wondering if it'd be possible to pass the renderer as a module instead of reading it from the `renderer` directory. I'd like the renderer to be internal to the framework and pass it to the plugin directly

**Comment by brillout** [comment] 2022-03-09 15:36
That's actually exactly what I'm working on as we speak.

There is already a beta `0.3.60.beta-4`. Stable release ETA this week.

You can see a little preview of it here: https://github.com/brillout/vps-framework.

What is it you want to build?

**Comment by pepicrft** [comment] 2022-03-11 17:15
Wow, that's amazing, thanks a lot 🙏🏼 
We are are stitching some blocks together to build an app framework, [GestaltJS](https://github.com/gestaltjs/gestalt), and I was looking for a Vite plugin that brought file-based routing capabilities to the Vite setup.

**Comment by brillout** [comment] 2022-03-12 18:41
Seems like a match 👍.

The goal of vps is two-fold:
 - Allow end-users to have control.
 - Allow frameworks to be built on top of it.

You can think of vps as a "framework builder".

Closing since this is not a bug report nor feature request.

**Closed by brillout** 2022-03-12 18:41 UTC

**Comment by pepicrft** [comment] 2022-03-25 16:01
Thanks a lot @brillout. I checked the project that you shared, and I can't get it working. This is how I initialize the plugin:
```js
ssr({pageFiles: [ frameworkDirectory, appDirectory ]})
```
But for some reason that I'm struggling to find, I get the following error:
```
Error: [vite-plugin-ssr@0.3.60][Wrong Usage] No `*.page.client.js` file found. Make sure to create one. You can create a `_default.page.client.js` which will apply as default to all your pages.
    at getPageClientPath (/Users/pepicrft/src/github.com/project/gestalt/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:357:29)
    at loadPageFiles (/Users/pepicrft/src/github.com/project/gestalt/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:323:28)
    at async renderPage (/Users/pepicrft/src/github.com/project/gestalt/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:80:23)
    at async renderPageWithoutThrowing (/Users/pepicrft/src/github.com/project/gestalt/node_modules/vite-plugin-ssr/dist/cjs/node/renderPage.js:131:16)
    at async file:///Users/pepicrft/src/github.com/project/gestalt/packages/app/dist/commands/app/dev.js:98605:27
[vite-plugin-ssr@0.3.60][Warning] No `_error.page.js` found. We recommend creating a `_error.page.js` file. (This warning is not shown in production.)
```

**Comment by brillout** [comment] 2022-03-25 16:04
Let me check

**Comment by brillout** [comment] 2022-03-25 16:05
I see. Let me finish the thing I'm working on right now, and I'll then update the example.

**Comment by brillout** [comment] 2022-03-25 19:45
Alright, https://github.com/brillout/vps-framework is now using the latest beta.

Let me know if you run into any issue.
