### ISSUE TITLE
CSS/Stylesheet Injected Twice Into Head

### ISSUE THREAD

**Issue by jrson83** [brillout/vite-plugin-ssr#261] opened 2022-02-14 14:51 UTC
Hey,
thanks for the great Plugin! I had a hard time with webpack & setting up dynamic imports. This is just working out of the box.

I'm having an issue with Stylesheets, which maybe related to vite, not this plugin, but to be sure I also post here.
I already replied to the existing [issue on vite](https://github.com/vitejs/vite/issues/4448).

I'm building a page with [preact-client-routing](https://github.com/brillout/vite-plugin-ssr/tree/master/examples/preact-client-routing) example as startpoint. The issue with multiple injected styles exists inside this untouched repo. Just clone and try.

I'm using the newest version of the example.

If running `npm run dev`  the `import './PageShell.css'` inside `PageShell.jsx` is injected as stylesheet and additionally as `<style />` tag in the head. You also see the styles always two times inside the styles inspector.

![2022-02-14_15h38_14](https://user-images.githubusercontent.com/45284565/153884864-f0ea911b-d81b-4ea0-8458-8174c591cbaf.png)

If running `npm run build` and `npm run server:prod` it is injected twice as stylesheet, here `_default.page.client.jsx.2942c7fb.css`.

![2022-02-14_15h39_07](https://user-images.githubusercontent.com/45284565/153885090-bf2f2a4d-1cbe-4ff4-b4bd-60dba5950dcd.png)

It would be great if this is fixed soon or eventually clarify if this is a vite issue.
Thanks.

**Comment by brillout** [comment] 2022-02-14 21:15
Just tried but couldln't reproduce with `examples/preact-react-client`.

Give me the exact steps you took to get there and I'll have another look.

**Comment by jrson83** [comment] 2022-02-14 23:20
> Just tried but couldln't reproduce with `examples/preact-react-client`.
> 
> Give me the exact steps you took to get there and I'll have another look.

Thanks for responding. I made a small Video to show the problem and [uploaded on Youtube](https://youtu.be/oubB0edEh1w).

**For dev**
1. git clone git@github.com:brillout/vite-plugin-ssr
2. cd vite-plugin-ssr/examples/preact-client-routing/
3. npm install
4. npm run dev
5. Copy & paste http://localhost:3000/ into browser and press enter
6. Inspect the source, you see `<style> Tag is injected
7. Reload CTRG+R, you see `<style> Tag is injected and above the `.css` stylesheet
8. In inspector style displayed two times, one time overwritten
9. If you don't see it refresh again

**For prod**
1. npm run build
2. npm run server:prod
3. Copy & paste http://localhost:3000/ into browser and press enter
4. Inspect the source, you see `.css` stylesheet injected as first and again a second time as last
5. In inspector style displayed two times, one time overwritten
6. If you don't see it refresh again

I also asked a friend to reproduce and he has the same issue. 

> Vite injects the css again after page load. Seems like there's a mismatch or something, Vite is not aware that the stylesheet is already loaded

**Comment by brillout** [comment] 2022-02-15 07:12
In dev this is expected since Vite does HMR.

I couldn't reproduce in prod. Both the DOM and the HTML didn't have any duplicated styles.

You are having backslashes `renderer\_default` instead of forward slashes `renderer/_default` in your duplicated styles. Are you using Windows? That may explain why I cannot reproduce.

It's most likely a Vite issue; closing this in favor of the Vite ticket.

**Closed by brillout** 2022-02-15 07:12 UTC

**Comment by jrson83** [comment] 2022-02-15 10:10
Okay, thanks for testing. Yeah, I'm using Windows. I will try if I have the same issue on Linux and report.

**Comment by jrson83** [comment] 2022-02-15 11:59
I have tested on Linux. When I run `dev` I have the issue, but when I run `build/prod` it works as it should and does not inject multiple style files.

**Comment by brillout** [comment] 2022-02-16 22:25
Good catch, will have a look at it tomorrow.

**Comment by brillout** [comment] 2022-02-17 14:42
Had a look and it's necessary to avoid CSS flashing. See comments in the commit.

Thanks for the digging.

**Comment by jrson83** [comment] 2022-02-17 17:26
> Had a look and it's necessary to avoid CSS flashing. See comments in the commit.
> 
> Thanks for the digging.

Awsome, thank you!

**Comment by wxin627** [comment] 2023-09-05 09:34
> Had a look and it's necessary to avoid CSS flashing. See comments in the commit.
> 
> Thanks for the digging.

Hi, I found out the injected link css file didn't support HMR for CSS Modules(.module.css) type, could you please confirm with that? @brillout

**Comment by brillout** [comment] 2023-09-05 11:46
> The injected link css file seems to not support HMR for CSS Modules(.module.css) type, I'm wondering if this is the root cause for page reload every time I update my `.module.css` file

Does it work with Vite without vite-plugin-ssr?

**Comment by wxin627** [comment] 2023-09-05 23:58
> > The injected link css file seems to not support HMR for CSS Modules(.module.css) type, I'm wondering if this is the root cause for page reload every time I update my `.module.css` file
> 
> Does it work with Vite without vite-plugin-ssr?

yes

**Comment by brillout** [comment] 2023-09-06 06:53
Can you publish two minimal reproductions: one showing that it works with Vite and another similar one showing that the same thing doesn't work with vite-plugin-ssr? That'd be the best. (FYI vite-plugin-ssr doesn't interfere with Vite's HMR so that's quite surprising.)

**Comment by wxin627** [comment] 2023-09-06 15:06
**Vite with vite-plugin-ssr**

1. open https://codesandbox.io/s/github/wxin627/vite-plugin-ssr-mvp
2. edit 'pages/index/test.module.css'
3. you'll see a log info in the terminal:  _[vite] page reload pages/index/test.module.css_ and page will reload

**Vite without vite-plugin-ssr**

1. open https://codesandbox.io/p/sandbox/github/wxin627/vite-react-mvp/tree/main
2. edit 'src/test.module.css'
3. you'll see a log info in the terminal: _[vite] hmr update /src/App.jsx_

**Comment by brillout** [comment] 2023-09-07 08:29
@wxin627 👌 I'll have a look at it after I'm done with the feature request I'm currently working on. Feel free to let me know if this is urgent for you.

**Comment by wxin627** [comment] 2023-09-07 09:01
> @wxin627 👌 I'll have a look at it after I'm done with the feature request I'm currently working on. Feel free to let me know if this is urgent for you.

not very urgent, take your time. 
just let me know if there's any progress, thank you!

**Comment by brillout** [comment] 2023-09-18 20:51
@wxin627 I could reproduce. I created a new ticket for it https://github.com/brillout/vite-plugin-ssr/issues/1127, although I still suspect the issue to be on Vite's side. I'll do a little bit of digging.
