### ISSUE TITLE
Proposal/Need help to improve MDX experience

### ISSUE THREAD

**Issue by jrson83** [brillout/vite-plugin-ssr#288] opened 2022-03-25 14:53 UTC
I spent almost all of last week integrating MDX into vite-plugin-ssr under certain prerequisites. I like to contribute to a better integration of `mdx-js` into the plugin for creating blogs or docs.

### Motivation

- Instead of using MDX files as `*.page.mdx` pages, it should be possible to render them in `*.page.jsx` or `*.page.tsx` files. The JSX file (parent) should render the MDX file as child
- This makes it possible to use the `<MDXProvider/>` to the full extent to modify the component tree
- It should be possible to get `export const documentProps` as well as `yaml-frontmatter` from the MDX files to access them in the `pageContext`
- MDX files shall not be compiled at runtime but at bundling time
- Nevertheless, it should be possible to automatically get a dynamic list of MDX files which can be consumed with `map` to build an overview of all posts/topics
- All MDX content should be rendered server-side, not only client-side, but with client-side routing

I assure I have read through the entire documentation more than 3x in the last days, I have searched every Github issue and the Discord channel and spent hours on every repo example. Some stuff I found helped me out. Today I have completed a presentable concept and hope through this post to either get tips on how I can improve the concept, perhaps could have achieved the whole thing much easier through existing functionality, or contribute through this concept to the plugin.

### What I tried so far

**From the docs:**

- [Route String](https://vite-plugin-ssr.com/route-string) & [Route Function](https://vite-plugin-ssr.com/route-function), [Page Redirection](https://vite-plugin-ssr.com/page-redirection), [Catch-All Routes](https://vite-plugin-ssr.com/catch-all), [Nested Routes](https://vite-plugin-ssr.com/nested-routes), File Structure, [Basic Apps](https://vite-plugin-ssr.com/file-structure#basic-apps) & [Domain-driven](https://vite-plugin-ssr.com/file-structure#domain-driven)
- onBeforeRender Hook, pageExports, routeParams & passToClient
- Different combinations of `*.page.route.*`, `_default` & for individuall pages, multiple `*.page.client.*` & `*.page.server.*` files (with and without `renderer` folder), `_default` & for individuall pages
- [Dynamic import](https://vite-plugin-ssr.com/dynamic-import), [Precedence](https://vite-plugin-ssr.com/route-function#precedence)

I was hoping it is possible with nested routes to render a MDX page in a JSX page, however I have not been able to do it.
Dynamic Import worked, but in the end it is not a satisfying option to render the MDX content only client-side.
Many other attempts failed because it is not possible to serialize functions or React components (at least I couldn't manage it).

### Example

Since I like to use `Preact` more then `React` and love client side routing, I used the `preact-client-routing` example as starter to build my concept example. I didn't use Typescript and I just added content which I think is necessary to comprehend the concept.

**Example tree:**

```
preact-client-routing-parent-child
├─ components
│  ├─ blog
│  │  ├─ BlogPost.jsx
│  │  └─ BlogPostTag.jsx
│  └─ mdx
│     ├─ MDXComponents.jsx
│     └─ MDXPre.jsx
├─ pages
│  ├─ blog
│  │  ├─ blog-01.page.mdx
│  │  ├─ blog-02.page.mdx
│  │  ├─ blog.page.jsx
│  │  ├─ index.page.jsx
│  │  ├─ index.page.route.jsx
│  │  └─ index.page.server.jsx
│  └─ index
│     ├─ Counter.jsx
│     └─ index.page.jsx
├─ renderer
│  ├─ getPosts.jsx
│  ├─ Link.jsx
│  ├─ logo.svg
│  ├─ PageShell.css
│  ├─ PageShell.jsx
│  ├─ usePageContext.jsx
│  ├─ _default.page.client.jsx
│  ├─ _default.page.server.jsx
│  └─ _error.page.jsx
├─ server
│  └─ index.js
└─ vite.config.js
```

#### Goal

**Blog list (overview)**
File which is rendered: `pages/blog/index.page.jsx`
Uses `renderer/index.page.server.jsx`, calls `renderer/getPosts.jsx` and passes `blogPosts` as `pageProps`
URL: http://localhost/blog

**Blog entry (single)***
File which is rendering the `.mdx` files: `pages/blog.page.jsx`
It is rendered through `function Content()` inside `renderer/pageShell.jsx`, which also passes the `MDXComponents`
URLs: http://localhost/blog/blog-01 & http://localhost/blog/blog-02

#### Repo

The example is on the master branch of this fork `preact-client-routing-parent-child`: https://github.com/jrson83/vite-plugin-ssr

All Test fail, but I guess this is just a showcase not a PR for an example.

I really care about the whole thing, because I really enjoy working with vite-plugin-ssr. If this idea can be achieved somehow easier or better, I would be very happy about an example how to achieve this.

**Sources:**
[MDX Provider](https://mdxjs.com/docs/using-mdx/#mdx-provider)
[Nuxtjs example nested pages](https://nuxtjs.org/examples/routing/nested-pages/)

**Issues which are somehow related or have some kind of same context:**
[Generate and route pages based on API data #123](https://github.com/brillout/vite-plugin-ssr/issues/123)
[Can't get dynamic component tree to SSR properly #127](https://github.com/brillout/vite-plugin-ssr/issues/127)
[ support for layout system #192](https://github.com/brillout/vite-plugin-ssr/issues/192)
[Using _default.page.xx files in pages directory #275](https://github.com/brillout/vite-plugin-ssr/issues/275)
[ More Tooling for Static Analysis of Pages #230](https://github.com/brillout/vite-plugin-ssr/issues/230)

**Comment by brillout** [comment] 2022-03-25 15:44
> I really care about the whole thing

I appreciate that. I also appreciate your perseverance.

I will reply later today.

**Comment by brillout** [comment] 2022-03-25 21:14
> * Instead of using MDX files as `*.page.mdx` pages, it should be possible to render them in `*.page.jsx` or `*.page.tsx` files. The JSX file (parent) should render the MDX file as child

That is already the case. E.g. vps's landing page does this.

> * It should be possible to get `export const documentProps` as well as `yaml-frontmatter` from the MDX files to access them in the `pageContext`

I strongly discourage building navigation from documentProps or frontmatter. Beyond the reason we discussed previously, it's also a fundamentally flawed approach because there is no clear way of defining the order of the navigation items. The straightforward way to define an order is to use an array, which is what `headings.ts` of the vps docs enables.

So I encourage using something like `headings.ts`.

As for the rest, I'd do it step-by-step. First a version that has only a couple of features, then progressively add the features you want. One by one. It's easier for me to give guidance then.

Closing since it's not a bug nor a feature request. But feel free to reply here.

**Closed by brillout** 2022-03-25 21:14 UTC

**Comment by naveennamani** [comment] 2022-04-01 15:37
@jrson83 #289 even i faced some problems while working with mdx-js, for now I was able to solve the issues with prerendering mdx content. Even I has started working just like you, but currently I need to cleanup my repo because of so much messing to solve the problems.
If it is of any help you can refer this project https://github.com/naveennamani/vite-ssr-mdx
And my blog post on dev.to https://dev.to/naveennamani/using-vite-plugin-ssr-with-mdx-js-solving-esm-only-library-problems-understanding-vite-configuration-and-writing-vite-plugins-3b24
I'll update you once I push my repo to GitHub

**Comment by jrson83** [comment] 2022-04-06 15:23
@naveennamani thanks for the answer and the example.

I did not have any problems or conflicts with setting up an ESM package, since I used the [react-full example](https://github.com/brillout/vite-plugin-ssr/tree/master/examples/react-full) as help, when setting up my project. Maybe check it out and convert your `.cjs` files to `.js` files, so you don't need the fix at all.

My example project is not online at the moment, since I needed the forked repo for PR's, but I will create a new repo soon, where you can checkout how I solved, to dynamically import `.mdx` files. I will reply soon.
