### ISSUE TITLE
Serverless Stack

### ISSUE THREAD

**Issue by ffxsam** [brillout/vite-plugin-ssr#232] opened 2021-12-15 08:22 UTC
Hi,

I'm attempting to set up a project consisting of [Serverless Stack](https://serverless-stack.com/) and Vite SSR (Vue). I've set up the following Lambda function:

```js
import { APIGatewayProxyHandlerV2 } from "aws-lambda";
import { createPageRenderer } from "vite-plugin-ssr";

const renderPage = createPageRenderer({
  isProduction: true,
  root: `${__dirname}/..`,
});

export const handler: APIGatewayProxyHandlerV2 = async (event) => {
  let url = event.rawPath;

  if (event.rawQueryString) {
    url += "?" + event.rawQueryString;
  }

  const pageContextInit = { url };
  const pageContext = await renderPage(pageContextInit);
  const { httpResponse } = pageContext;
  if (!httpResponse) return { statusCode: 200, body: "??" };
  const { body, statusCode, contentType } = httpResponse;

  return {
    statusCode,
    headers: { "Content-Type": contentType },
    body,
  };
};
```

And when I invoke the function by opening the API Gateway URL in my browser, I get:

```
Error: [vite-plugin-ssr@0.3.36][Internal Failure] You stumbled upon a bug in the source code of vite-plugin-ssr (an internal assertion failed). This should not be happening: please reach out at https://github.com/brillout/vite-plugin-ssr/issues/new or https://discord.com/invite/qTq92FQzKb and include this error stack (the error stack is usually enough to fix the problem). Please do reach out as it helps make vite-plugin-ssr more robust. A fix will be written promptly (usually under 24 hours).
    at setPageFiles (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:1017:27)
    at getAllPageFiles (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:878:43)
    at getGlobalContext (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:3863:69)
    at initializePageContext (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:3349:35)
    at renderPage2 (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:3261:33)
    at renderPageWithoutThrowing (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:3357:34)
    at Runtime.handler (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/.sst/artifacts/3fa176ba/src/lambda.js:4067:29)
    at Runtime.handleOnce (/Volumes/SuperData/Sites/reelcrafter/v2-presentation2/node_modules/@serverless-stack/aws-lambda-ric/lib/Runtime/Runtime.js:76:33)
```

Let me know if you'd like access to the full project.

**Comment by brillout** [comment] 2021-12-15 08:47
Let me have a look

**Comment by ffxsam** [comment] 2021-12-15 09:04
Thanks! I can upload the project tomorrow.

**Comment by brillout** [comment] 2021-12-15 09:05
Seems to be a problem with your server environment.

Do you get the error in both dev and prod?

> Let me know if you'd like access to the full project.

That would actually be the easiest yes. Especially if you get the problem also in dev, that would easy for me to debug then.

**Comment by ffxsam** [comment] 2021-12-15 18:05
Ok, the project is here: https://github.com/ffxsam/v2-presentation2

The Vite code is borrowed from https://github.com/jamesladd/aws-vite-ssr.

To answer your question about dev & prod.. it's a bit complicated.

With Serverless Stack (SST), there is no "offline" dev mode that behaves differently than production (like Serverless Framework). With SST, when you run `yarn start`, it's actually installing some hooks on the AWS side so that when you invoke an API Gateway call, it calls the Lambda function in the cloud which connects back to your local machine to execute the code, then reports the result back to AWS. There's a ton of benefits to this. More details here: https://docs.serverless-stack.com/live-lambda-development

So the short answer is, I'd probably never run Vite's `yarn dev`, and instead run SST's `yarn start` and then point my browser to the API Gateway URL which would be just like real calls to the web app in production.

Instructions for setting this up:

- Clone the repo, then run `yarn`.
- Run `yarn start` - this will deploy two CloudFormation stacks (three if you count the standard CDK bootstrap stack), one is for the special live debugging feature I mentioned, the other is the actual application itself.
- After a short time, you'll get an API Gateway endpoint URL in your console, and you'll be able to open that in your browser to test. All API Gateway requests/responses will be shown in your console.

I've probably done this completely wrong, but I'm far from an expert in SSR apps! Any help is appreciated. Thanks!

**Comment by ffxsam** [comment] 2021-12-15 18:30
I realize [this line](https://github.com/ffxsam/v2-presentation2/blob/main/src/lambda.ts#L6) should probably vary depending on whether we're running locally or not (`process.env.IS_LOCAL`). When local, the JS code is several levels deep (`.sst/build/artifacts/xx...`) but in production that won't be the case. Not exactly sure what it should be yet, as I don't fully understand the structure.

**Comment by brillout** [comment] 2021-12-16 08:36
@ffxsam The best would be a minimal reproduction being basically the Vue boilerplate (`npm init vite-plugin-ssr@latest` -> `vue`) + SST.

(We could then have a `examples/serverless-stack/` that is tested upon each release; like how Cloudflare is being tested with `.test*` files at https://github.com/brillout/vite-plugin-ssr/tree/master/examples/cloudflare-workers.)

That would ensure that the SST integration keeps working "forever".

**Comment by brillout** [comment] 2021-12-16 08:37
> @ffxsam The best would be a minimal reproduction being basically the Vue boilerplate (`npm init vite-plugin-ssr@latest` -> `vue`) + SST.

Actually it would be even better if it's a minimal reproduction based off `examples/vue/` (it's more minimal than the Vue boilerplate).

**Comment by ffxsam** [comment] 2021-12-16 09:09
Sure thing, I'll work on that when I get some spare time. I think it'd be great to have a working SST example! Then I can let the SST team know, in case they want to link to this repo or do a small write-up.

**Comment by ffxsam** [comment] 2021-12-17 21:37
Well, I'm stumped. This is where the error is being thrown, though:
https://github.com/brillout/vite-plugin-ssr/blob/09f86058d9f63475b6a7d319c5a3f6b550ed6d7a/vite-plugin-ssr/node/page-files/setup.ts#L14

It's looking for `pageFiles.js` in the SST temporary build directory (when in local dev) which is `.sst/artifacts/<hash>/src`. All that's in that folder is my Lambda function handler. `__dirname` is hardcoded in the line above, so I don't know how to point it elsewhere.

I figure the process here would loosely be:

1. `yarn vite build && yarn vite build --ssr` (somehow this works in the root directory even though the Vite files are in `vue/`)
2. `yarn start` (start SST local dev process)
3. Visit API URL
4. vite-plugin-ssr looks in `dist/` for files, not in the SST artifacts folder

The repo has been updated: https://github.com/ffxsam/v2-presentation2

**Comment by ffxsam** [comment] 2021-12-17 22:05
I think there's something on the SST side where I can have it run `vite build --outDir xyz && vite build --ssr --outDir xyz` and have it go into the proper folder for bundling up with the Lambda entry JS file. I'm looking into it.

**Comment by ffxsam** [comment] 2021-12-17 22:30
Made a few more updates. Try this:

1. `yarn build:vite`
2. `yarn deploy --stage prod`

Once you get an API URL, visit that, and you'll see "??". Check out the CloudWatch logs for the test function, and look at the `pageContext` object.

Weird stuff:
I had to copy `dist/server` twice into the artifacts, because vite-plugin-ssr is looking for `pageFiles.js` in two locations for some reason.

I think this is probably as far as I can get without help.

**Comment by brillout** [comment] 2021-12-18 11:46
I will have a look at it tentatively today.

**Comment by brillout** [comment] 2021-12-21 22:39
Actually: did you add [`importBuild.js`](https://vite-plugin-ssr.com/importBuild.js)?

**Comment by brillout** [comment] 2021-12-21 22:41
Just checked your reproduction and I'm not seeing `importBuild.js`. Let me know if you still have problems when using `importBuild.js`.

`vite-plugin-ssr` should improve the error message which I'll fix.

**Comment by ffxsam** [comment] 2021-12-21 22:44
I see `dist/server/importBuild.js` after I run `yarn build:vite`.

```
vite v2.7.2 building for production...
✓ 62 modules transformed.
dist/client/vite-plugin-ssr.json                                       0.07 KiB
dist/client/manifest.json                                              1.36 KiB
dist/client/assets/vue/renderer/_default.page.client.js.4c64af3e.js    0.79 KiB / gzip: 0.49 KiB
dist/client/assets/index.page.631402d4.js                              0.29 KiB / gzip: 0.23 KiB
dist/client/assets/index.page.131e885d.js                              0.66 KiB / gzip: 0.42 KiB
dist/client/assets/_default.page.server.24778d95.js                    0.05 KiB / gzip: 0.06 KiB
dist/client/assets/vue/renderer/_default.page.client.js.4a6be9ad.css   0.41 KiB / gzip: 0.26 KiB
dist/client/assets/index.page.de42b54a.css                             0.02 KiB / gzip: 0.04 KiB
dist/client/assets/vendor.f5258edb.js                                  66.20 KiB / gzip: 26.11 KiB
vite v2.7.2 building SSR bundle for production...
✓ 12 modules transformed.
dist/server/importBuild.js                                0.71 KiB
dist/server/package.json                                  0.02 KiB
dist/server/manifest.json                                 1.51 KiB
dist/server/pageFiles.js                                  0.81 KiB
dist/server/assets/index.page.6f6eacde.js                 0.76 KiB
dist/server/assets/plugin-vue_export-helper.db096aab.js   0.20 KiB
dist/server/assets/index.page.1d6cece2.js                 1.79 KiB
dist/server/assets/_default.page.client.a21de7cc.js       0.19 KiB
dist/server/assets/_default.page.server.eaedb281.js       2.03 KiB
```

**Comment by brillout** [comment] 2021-12-21 22:52
See https://vite-plugin-ssr.com/importBuild.js

**Comment by ffxsam** [comment] 2021-12-21 23:31
Ah, apologies. I'll review that and get back to you. 👍

**Comment by ffxsam** [comment] 2021-12-21 23:41
Ok, we're making progress (and I've updated the repo again). No more errors, but the response from `renderPage()` includes a null `httpResponse`.

```js
{
  _isPreRendering: false,
  url: '/',
  _isPageContextRequest: false,
  _parseUrl: [Function: _parseUrl],
  _baseUrl: '/',
  _allPageFiles: {
    '.page': [
      {
        filePath: '/vue/pages/about/index.page.vue',
        loadFile: [Function: /vue/pages/about/index.page.vue]
      },
      {
        filePath: '/vue/pages/index/index.page.vue',
        loadFile: [Function: /vue/pages/index/index.page.vue]
      }
    ],
    '.page.route': [],
    '.page.server': [
      {
        filePath: '/vue/renderer/_default.page.server.js',
        loadFile: [Function: /vue/renderer/_default.page.server.js]
      }
    ],
    '.page.client': [
      {
        filePath: '/vue/renderer/_default.page.client.js',
        loadFile: [Function: /vue/renderer/_default.page.client.js]
      }
    ]
  },
  _allPageIds: [ '/vue/pages/about/index', '/vue/pages/index/index' ],
  _pageRoutes: [
    { pageId: '/vue/pages/about/index', filesystemRoute: '/vue/about' },
    { pageId: '/vue/pages/index/index', filesystemRoute: '/vue' }
  ],
  _onBeforeRouteHook: null,
  urlPathname: [Getter],
  urlParsed: [Getter],
  _pageId: null,
  routeParams: {},
  httpResponse: null
}
```

**Comment by brillout** [comment] 2021-12-22 06:42
Go to `/vue` and you'll see what is happening.

You can use https://vite-plugin-ssr.com/filesystemRoutingRoot to achieve what you want.

**Comment by ffxsam** [comment] 2021-12-22 07:07
Got it - thanks!

Would you prefer I open a PR & continue working there? There's still quite a bit to do, and perhaps others may want to contribute.

**Comment by brillout** [comment] 2021-12-22 07:59
Yea let's make a PR for `examples/sst` :-)

**Comment by brillout** [comment] 2021-12-24 02:16
Closing; let's continue this in a PR :-).

**Closed by brillout** 2021-12-24 02:16 UTC
Labels: being-inspected :microscope:

**Comment by ffxsam** [comment] 2022-02-11 17:47
@brillout Sorry it took so long, things have been busy here!

https://github.com/brillout/vite-plugin-ssr/pull/260/
