### ISSUE TITLE
After build, if there is an error in the script in the code, it will cause a white screen instead of entering the error page

### ISSUE THREAD

**Issue by sunseekers** [brillout/vite-plugin-ssr#687] opened 2023-03-08 02:52 UTC
### Description

If there is an error in the script, a white screen page will appear instead of entering 500

I hope that there will be no white screen of the page under any circumstances, either a 404 page or a 500

**Comment by brillout** [comment] 2023-03-08 09:32
I agree. I'll need a reproduction.

**Comment by sunseekers** [comment] 2023-03-10 07:36
1. pnpm create vite-plugin-ssr
2. Add a sentence to the pages/index/index.page.vue  script  file of the project such as：
const xx = newBook.bookList.content
  .replace(/\r\n/g, '\n')
  .replace(/(\n[\r|\s|\t]*)+/g, '\n')
  .replace(/\r/g, '\n')
  .trim()
<img width="839" alt="image" src="https://user-images.githubusercontent.com/25503586/224252674-2d94aa33-e3cc-41d6-b8eb-eed66ae577ea.png">

3.  pnpm dev => http://localhost:3000 
4. 500 Interwewewnal Server Error

pnpm dev as expected

If after building : pnpm build  pnpm server:prod => http://localhost:3000 
not as expected because  page white screen

**Comment by sunseekers** [comment] 2023-03-10 07:37
> I agree. I'll need a reproduction.
pnpm create vite-plugin-ssr
Add a sentence to the pages/index/index.page.vue script file of the project such as：
const xx = newBook.bookList.content
.replace(/\r\n/g, '\n')
.replace(/(\n[\r|\s|\t]*)+/g, '\n')
.replace(/\r/g, '\n')
.trim()
image

pnpm dev => http://localhost:3000/
500 Interwewewnal Server Error
pnpm dev as expected

If after building : pnpm build pnpm server:prod => http://localhost:3000/
not as expected because page white screen

**Comment by sunseekers** [comment] 2023-03-10 07:42
> I agree. I'll need a reproduction.

1. pnpm create vite-plugin-ssr
2. Add a sentence to the pages/index/index.page.vue script file of the project such as：
```
  const xx = newBook.bookList.content
  .replace(/\r\n/g, '\n')
  .replace(/(\n[\r|\s|\t]*)+/g, '\n')
  .replace(/\r/g, '\n')
  .trim()
```
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/25503586/224253947-4729d4d7-32a1-4077-87d7-4481a18dee38.png">



```
pnpm dev 

as expected because 500 Interwewewnal Server Error
```

```

pnpm build 

pnpm server:prod

not as expected because page white screen
```

**Comment by sunseekers** [comment] 2023-03-10 08:01
> I agree. I'll need a reproduction.

1. pnpm create vite-plugin-ssr

2. Add a sentence to the pages/index/index.page.vue script file of the project such as：
`throw new Error()`
<img width="803" alt="image" src="https://user-images.githubusercontent.com/25503586/224257584-e57b51c8-fd47-4d8e-af84-1ba77e28f4a1.png">


```
pnpm dev 

as expected because 500 Interwewewnal Server Error
```

```
pnpm build 

pnpm server:prod

not as expected because page white screen
```

**Comment by hellohejinyu** [comment] 2023-03-10 08:13
![image](https://user-images.githubusercontent.com/8766034/224259809-bc6c0ca0-31d6-496d-8ba0-a6c7d2e1bd0d.png)
![image](https://user-images.githubusercontent.com/8766034/224260070-7c35dd09-5967-4e8d-9893-e0bc6b20ae5c.png)

I observed that if an error is reported in the setup, the template data will be lost in the build product. I don't know much about vue ssr and I don't know if this is intended by design.

**Comment by brillout** [comment] 2023-03-10 09:20
@sunseekers Indeed, I could reproduce. I'll have a look at it.

@hellohejinyu Intersting. Maybe it lives in another file? Have you compared without `throw new Error()`?

**Comment by brillout** [comment] 2023-03-10 18:07
It's a Vue bug, see https://github.com/vuejs/core/issues/7876.

**Comment by brillout** [comment] 2023-03-10 18:08
It's a Vue bug. Closing in favor of https://github.com/vuejs/core/issues/7876.

**Closed by brillout** 2023-03-10 18:08 UTC
Labels: bug :boom:

**Comment by brillout** [comment] 2023-04-18 11:57
Workaround: https://github.com/brillout/vite-plugin-ssr/commit/169677a1781f66d26c662e5529313599c5e275e8.

For more context: https://github.com/vuejs/core/issues/7876#issuecomment-1512899954.
